"""Esquema inicial: Etapa 0 (infraestructura) + Etapa P1 (identidad y acceso)
+ Etapa P2 (curso, equipo docente y permisos) + Etapa P3 (vinculacion Canvas)
+ Etapa P4 (vinculacion GitHub y checklist de verificacion) + Etapa P5
(espejo de Canvas: estudiantes, secciones y grupos) + Etapa P6 (mapeo
estudiante <-> GitHub y Pendientes) + Etapa P7 (tarea individual, entrega
unica y repositorio base) + Etapa P8 (aprovisionamiento, estado, aviso al
estudiante y lectura de fechas).

Revision ID: 0001
Revises:
Create Date: 2026-09-12

Esta es LA UNICA MIGRACION DEL PROYECTO (SPEC 14 S14.8.1, A-175, RG-144,
RG-193). Se regenera con `alembic revision --autogenerate --rev-id 0001`
sobre una base vacia cada vez que una etapa nueva añade tablas, mientras
estemos antes del 16-sep-2026 -- nunca se crea una revision 0002 antes de esa
fecha. Despues del 16-sep, S14.8.2 permite solo cambios aditivos, y esos si
van en una revision nueva.

Claves primarias UUIDv7 en toda tabla con `id` propio (ARQUITECTURA.md S8):
"nunca un identificador externo como clave primaria". `cubo_tasa` y
`estado_sistema` son la excepcion deliberada -- su clave es natural.

Generada con `alembic revision --autogenerate` a partir de los modelos de
app/adaptadores/modelos_infraestructura.py, modelos_identidad.py,
modelos_curso.py, modelos_canvas.py, modelos_github.py, modelos_padron.py,
modelos_mapeo.py y modelos_tarea.py, y verificada con `alembic check` (cero
divergencia) contra Postgres 16 real.

La FK `tarea.repositorio_base_id -> repositorio_base.id` cierra el ciclo que
declara A-080 y se crea con `create_foreign_key` despues de ambas tablas (y se
retira primero en `downgrade`).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cubo_tasa",
        sa.Column("clave", sa.Text(), nullable=False),
        sa.Column("ventana_inicio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("contador", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("clave", "ventana_inicio", name=op.f("pk_cubo_tasa")),
    )
    op.create_table(
        "cuenta_github",
        sa.Column("github_user_id", sa.BigInteger(), nullable=False),
        sa.Column("login", sa.Text(), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("revalidado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('VALIDA', 'RENOMBRADA', 'NO_EXISTE', 'ES_ORGANIZACION')",
            name=op.f("ck_cuenta_github_estado_valido"),
        ),
        sa.CheckConstraint(
            "tipo IN ('USER', 'ORGANIZATION', 'BOT')", name=op.f("ck_cuenta_github_tipo_valido")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cuenta_github")),
    )
    op.create_index(
        "uq_cuenta_github_github_user_id", "cuenta_github", ["github_user_id"], unique=True
    )
    op.create_table(
        "estado_sistema",
        sa.Column("clave", sa.Text(), nullable=False),
        sa.Column("valor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("clave", name=op.f("pk_estado_sistema")),
    )
    op.create_table(
        "presupuesto_api",
        sa.Column("ambito", sa.Text(), nullable=False),
        sa.Column("ambito_id", sa.Text(), nullable=False),
        sa.Column("cubo", sa.Text(), nullable=False),
        sa.Column("capacidad", sa.Integer(), nullable=False),
        sa.Column("restante", sa.Integer(), nullable=False),
        sa.Column("reinicio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_presupuesto_api")),
        sa.UniqueConstraint("ambito", "ambito_id", "cubo", name=op.f("uq_presupuesto_api_ambito")),
    )
    op.create_table(
        "respaldo",
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("exitoso", sa.Boolean(), nullable=False),
        sa.Column("tamano_bytes", sa.BigInteger(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_respaldo")),
        sa.UniqueConstraint("fecha", name=op.f("uq_respaldo_fecha")),
    )
    op.create_table(
        "resultado_invariante",
        sa.Column("invariante", sa.Text(), nullable=False),
        sa.Column("cumple", sa.Boolean(), nullable=False),
        sa.Column("detalle", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resultado_invariante")),
    )
    op.create_table(
        "usuario",
        sa.Column("google_sub", sa.Text(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("email_canonico", postgresql.CITEXT(), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("cuenta_github_id", sa.Integer(), nullable=True),
        sa.Column("github_login_declarado", sa.Text(), nullable=True),
        sa.Column("consentimiento_github_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("generacion_enlaces", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "email LIKE '%%@gmail.com'", name=op.f("ck_usuario_email_dominio_gmail")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuario")),
        sa.UniqueConstraint("email", name=op.f("uq_usuario_email")),
        sa.UniqueConstraint("email_canonico", name=op.f("uq_usuario_email_canonico")),
        sa.UniqueConstraint("google_sub", name=op.f("uq_usuario_google_sub")),
    )
    op.create_index(
        "uq_usuario_cuenta_github_id",
        "usuario",
        ["cuenta_github_id"],
        unique=True,
        postgresql_where=sa.text("cuenta_github_id IS NOT NULL"),
    )
    op.create_table(
        "curso",
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("codigo", sa.Text(), nullable=False),
        sa.Column("periodo", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("zona_horaria", sa.Text(), nullable=False),
        sa.Column("umbral_dias_sin_actividad", sa.Integer(), nullable=False),
        sa.Column("umbral_desbalance_pct", sa.Integer(), nullable=False),
        sa.Column("canvas_base_url", sa.Text(), nullable=True),
        sa.Column("canvas_course_id", sa.BigInteger(), nullable=True),
        sa.Column("github_org_login", sa.Text(), nullable=True),
        sa.Column("github_org_id", sa.BigInteger(), nullable=True),
        sa.Column("github_installation_id", sa.BigInteger(), nullable=True),
        sa.Column("via_anuncio_seccion", sa.Text(), nullable=False),
        sa.Column("canal_comunicacion_activo", sa.Text(), nullable=True),
        sa.Column("canvas_assignment_id_registro", sa.BigInteger(), nullable=True),
        sa.Column("registro_creado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registro_creado_por", sa.UUID(), nullable=True),
        sa.Column("registro_estado", sa.Text(), nullable=False),
        sa.Column("registro_huella_config", sa.LargeBinary(), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "canal_comunicacion_activo IS NULL OR canal_comunicacion_activo IN ('CONVERSACION', 'COMENTARIO_ENTREGA', 'BLOQUEADO')",
            name=op.f("ck_curso_canal_comunicacion_activo_valido"),
        ),
        sa.CheckConstraint(
            "estado IN ('BORRADOR', 'VINCULANDO', 'ACTIVO', 'CANVAS_DESVINCULADO', 'GITHUB_DESVINCULADO', 'ARCHIVADO')",
            name=op.f("ck_curso_estado_valido"),
        ),
        sa.CheckConstraint(
            "registro_estado IN ('NO_CREADA', 'ACTIVA', 'ALTERADA', 'DESAPARECIDA')",
            name=op.f("ck_curso_registro_estado_valido"),
        ),
        sa.CheckConstraint(
            "via_anuncio_seccion IN ('SECCION', 'CURSO', 'NINGUNA', 'NO_VERIFICADO')",
            name=op.f("ck_curso_via_anuncio_seccion_valida"),
        ),
        sa.CheckConstraint("length(codigo) <= 12", name=op.f("ck_curso_codigo_longitud_maxima")),
        sa.CheckConstraint("length(periodo) = 6", name=op.f("ck_curso_periodo_longitud_exacta")),
        sa.CheckConstraint("length(slug) <= 24", name=op.f("ck_curso_slug_longitud_maxima")),
        sa.ForeignKeyConstraint(
            ["registro_creado_por"],
            ["usuario.id"],
            name=op.f("fk_curso_registro_creado_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curso")),
        sa.UniqueConstraint("slug", name=op.f("uq_curso_slug")),
    )
    op.create_index(
        "uq_curso_github_installation_id", "curso", ["github_installation_id"], unique=True
    )
    op.create_index("uq_curso_github_org_id", "curso", ["github_org_id"], unique=True)
    op.create_table(
        "identidad_canvas_usuario",
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("canvas_base_url", sa.Text(), nullable=False),
        sa.Column("canvas_user_id", sa.BigInteger(), nullable=False),
        sa.Column("verificada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ultima_confirmacion_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_identidad_canvas_usuario_usuario_id_usuario"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identidad_canvas_usuario")),
    )
    op.create_index(
        "uq_identidad_canvas_base_url_canvas_user_id",
        "identidad_canvas_usuario",
        ["canvas_base_url", "canvas_user_id"],
        unique=True,
    )
    op.create_index(
        "uq_identidad_canvas_usuario_id_base_url",
        "identidad_canvas_usuario",
        ["usuario_id", "canvas_base_url"],
        unique=True,
    )
    op.create_table(
        "sesion",
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("jti_oidc", sa.Text(), nullable=False),
        sa.Column("creada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expira_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revocada_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agente", sa.Text(), nullable=True),
        sa.Column("ip_truncada", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_sesion_usuario_id_usuario"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sesion")),
        sa.UniqueConstraint("jti_oidc", name=op.f("uq_sesion_jti_oidc")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sesion_token_hash")),
    )
    op.create_index("ix_sesion_usuario_id", "sesion", ["usuario_id"], unique=False)
    op.create_table(
        "bitacora",
        sa.Column("curso_id", sa.UUID(), nullable=True),
        sa.Column("accion", sa.Text(), nullable=False),
        sa.Column("entidad", sa.Text(), nullable=False),
        sa.Column("entidad_id", sa.Text(), nullable=True),
        sa.Column("actor_usuario_id", sa.UUID(), nullable=True),
        sa.Column("permiso_exigido", sa.Text(), nullable=True),
        sa.Column("ruta", sa.Text(), nullable=True),
        sa.Column("metodo", sa.Text(), nullable=True),
        sa.Column("antes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("despues", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_usuario_id"],
            ["usuario.id"],
            name=op.f("fk_bitacora_actor_usuario_id_usuario"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"], ["curso.id"], name=op.f("fk_bitacora_curso_id_curso"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bitacora")),
    )
    op.create_index(
        "ix_bitacora_curso_id_creado_en", "bitacora", ["curso_id", "creado_en"], unique=False
    )
    op.create_table(
        "conjunto_grupos",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("canvas_group_category_id", sa.BigInteger(), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("no_colaborativo", sa.Boolean(), nullable=False),
        sa.Column("self_signup", sa.Text(), nullable=True),
        sa.Column("group_limit", sa.Integer(), nullable=True),
        sa.Column("auto_leader", sa.Text(), nullable=True),
        sa.Column("sincronizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_conjunto_grupos_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conjunto_grupos")),
    )
    op.create_index(
        "uq_conjunto_grupos_curso_id_canvas_group_category_id",
        "conjunto_grupos",
        ["curso_id", "canvas_group_category_id"],
        unique=True,
    )
    op.create_table(
        "credencial_canvas",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("token_cifrado", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("huella", sa.Text(), nullable=False),
        sa.Column("canvas_user_id", sa.BigInteger(), nullable=False),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("orden_respaldo", sa.Integer(), nullable=False),
        sa.Column("version_clave", sa.SmallInteger(), nullable=False),
        sa.Column("consentimiento_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ultimo_chequeo_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_error", sa.Text(), nullable=True),
        sa.Column("fallos_403_consecutivos", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('VALIDA', 'INVALIDA', 'RETIRADA')",
            name=op.f("ck_credencial_canvas_estado_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_credencial_canvas_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_credencial_canvas_usuario_id_usuario"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credencial_canvas")),
    )
    op.create_index(
        "uq_credencial_canvas_curso_id_usuario_id",
        "credencial_canvas",
        ["curso_id", "usuario_id"],
        unique=True,
    )
    op.create_index(
        "uq_credencial_canvas_operativa_por_curso",
        "credencial_canvas",
        ["curso_id"],
        unique=True,
        postgresql_where=sa.text("orden_respaldo = 0"),
    )
    op.create_table(
        "cursor_sincronizacion",
        sa.Column("curso_id", sa.UUID(), nullable=True),
        sa.Column("recurso", sa.Text(), nullable=False),
        sa.Column("referencia", sa.Text(), nullable=False),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("ultimo_head_sha", sa.Text(), nullable=True),
        sa.Column("per_page_medido", sa.Integer(), nullable=True),
        sa.Column("ultimo_exito_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_backfill_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estado", sa.Text(), nullable=True),
        sa.Column("ultimo_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_cursor_sincronizacion_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cursor_sincronizacion")),
        sa.UniqueConstraint(
            "curso_id", "recurso", "referencia", name=op.f("uq_cursor_sincronizacion_curso_id")
        ),
    )
    op.create_table(
        "equipo_github_curso",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=True),
        sa.Column("team_slug", sa.Text(), nullable=True),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("via_efectiva", sa.Text(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ultimo_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('ACTIVO', 'ERROR')", name=op.f("ck_equipo_github_curso_estado_valido")
        ),
        sa.CheckConstraint(
            "via_efectiva IN ('TEAM', 'COLABORADOR')",
            name=op.f("ck_equipo_github_curso_via_efectiva_valida"),
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_equipo_github_curso_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipo_github_curso")),
    )
    op.create_index(
        "uq_equipo_github_curso_curso_id", "equipo_github_curso", ["curso_id"], unique=True
    )
    op.create_table(
        "estudiante",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("canvas_user_id", sa.BigInteger(), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("nombre_ordenable", sa.Text(), nullable=True),
        sa.Column("login_id", sa.Text(), nullable=True),
        sa.Column("sis_user_id", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("uuid", sa.Text(), nullable=True),
        sa.Column("past_uuid", sa.Text(), nullable=True),
        sa.Column("group_ids_canvas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("ciclos_ausente", sa.Integer(), nullable=False),
        sa.Column("primera_vista_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ultima_vista_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retirado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_recordatorio_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('ACTIVO', 'INVITADO', 'INACTIVO', 'CONCLUIDO', 'RETIRADO')",
            name=op.f("ck_estudiante_estado_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_estudiante_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estudiante")),
    )
    op.create_index(
        "uq_estudiante_curso_id_canvas_user_id",
        "estudiante",
        ["curso_id", "canvas_user_id"],
        unique=True,
    )
    op.create_table(
        "incidencia",
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("severidad", sa.Text(), nullable=False),
        sa.Column("sujeto_tipo", sa.Text(), nullable=False),
        sa.Column("sujeto_id", sa.UUID(), nullable=True),
        sa.Column("curso_id", sa.UUID(), nullable=True),
        sa.Column("detalle", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("abierta", sa.Boolean(), nullable=False),
        sa.Column("resuelta_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("silenciada", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_incidencia_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidencia")),
    )
    op.create_index("ix_incidencia_abierta", "incidencia", ["abierta"], unique=False)
    op.create_table(
        "instalacion_github",
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("curso_id", sa.UUID(), nullable=True),
        sa.Column("org_login", sa.Text(), nullable=False),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("repository_selection", sa.Text(), nullable=False),
        sa.Column("permisos_pendientes", sa.Boolean(), nullable=False),
        sa.Column("suspendida", sa.Boolean(), nullable=False),
        sa.Column("actualizada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_instalacion_github_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instalacion_github")),
    )
    op.create_index(
        "uq_instalacion_github_curso_id", "instalacion_github", ["curso_id"], unique=True
    )
    op.create_index(
        "uq_instalacion_github_installation_id",
        "instalacion_github",
        ["installation_id"],
        unique=True,
    )
    op.create_table(
        "intento_instalacion_github",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("jti", sa.Text(), nullable=False),
        sa.Column("org_login_sugerido", sa.Text(), nullable=True),
        sa.Column("emitido_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumido_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_intento_instalacion_github_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_intento_instalacion_github_usuario_id_usuario"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intento_instalacion_github")),
        sa.UniqueConstraint("jti", name=op.f("uq_intento_instalacion_github_jti")),
    )
    op.create_table(
        "invitacion_equipo",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("email_canonico", postgresql.CITEXT(), nullable=False),
        sa.Column("rol", sa.Text(), nullable=False),
        sa.Column("permisos", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("github_login_declarado", sa.Text(), nullable=True),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("invitada_por", sa.UUID(), nullable=False),
        sa.Column("creada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expira_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("aceptada_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocada_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocada_por", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(rol <> 'PROFESOR' OR permisos = '{}')",
            name=op.f("ck_invitacion_equipo_invitacion_equipo_permisos_vacio_para_profesor"),
        ),
        sa.CheckConstraint(
            "NOT (rol = 'AYUDANTE' AND permisos && ARRAY['curso.administrar','equipo.administrar']::text[])",
            name=op.f("ck_invitacion_equipo_invitacion_equipo_permisos_no_concedible_a_ayudante"),
        ),
        sa.CheckConstraint(
            "estado IN ('PENDIENTE', 'ACEPTADA', 'REVOCADA', 'EXPIRADA')",
            name=op.f("ck_invitacion_equipo_estado_valido"),
        ),
        sa.CheckConstraint(
            "permisos <@ ARRAY['tarea.administrar','correccion.asignar','nota.publicar','comunicacion.enviar','curso.administrar','equipo.administrar','mapeo.editar']::text[]",
            name=op.f("ck_invitacion_equipo_invitacion_equipo_permisos_catalogo_cerrado"),
        ),
        sa.CheckConstraint(
            "rol IN ('PROFESOR', 'AYUDANTE')", name=op.f("ck_invitacion_equipo_rol_valido")
        ),
        sa.CheckConstraint(
            "array_position(permisos, NULL) IS NULL",
            name=op.f("ck_invitacion_equipo_invitacion_equipo_permisos_sin_null"),
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_invitacion_equipo_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invitada_por"],
            ["usuario.id"],
            name=op.f("fk_invitacion_equipo_invitada_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revocada_por"],
            ["usuario.id"],
            name=op.f("fk_invitacion_equipo_revocada_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitacion_equipo")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitacion_equipo_token_hash")),
    )
    op.create_index(
        "uq_invitacion_equipo_curso_id_email_canonico_pendiente",
        "invitacion_equipo",
        ["curso_id", "email_canonico"],
        unique=True,
        postgresql_where=sa.text("estado = 'PENDIENTE'"),
    )
    op.create_table(
        "membresia_curso",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("rol", sa.Text(), nullable=False),
        sa.Column("permisos", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("es_via_compartida", sa.Boolean(), nullable=False),
        sa.Column("org_github_alta_por_app", sa.Boolean(), nullable=False),
        sa.Column("org_github_estado", sa.Text(), nullable=True),
        sa.Column("org_github_invitada_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_github_activa_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_github_reenvios", sa.Integer(), nullable=False),
        sa.Column("org_github_ultimo_reenvio_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_github_ultimo_error", sa.Text(), nullable=True),
        sa.Column("invitada_por", sa.UUID(), nullable=True),
        sa.Column("creada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retirada_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retirada_por", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(rol <> 'PROFESOR' OR permisos = '{}')",
            name=op.f("ck_membresia_curso_membresia_curso_permisos_vacio_para_profesor"),
        ),
        sa.CheckConstraint(
            "NOT (rol = 'AYUDANTE' AND permisos && ARRAY['curso.administrar','equipo.administrar']::text[])",
            name=op.f("ck_membresia_curso_membresia_curso_permisos_no_concedible_a_ayudante"),
        ),
        sa.CheckConstraint(
            "estado IN ('ACTIVA', 'RETIRADA')", name=op.f("ck_membresia_curso_estado_valido")
        ),
        sa.CheckConstraint(
            "org_github_estado IS NULL OR org_github_estado IN ('NO_APLICA', 'SIN_CONSENTIMIENTO', 'PENDIENTE', 'ACTIVA', 'ERROR')",
            name=op.f("ck_membresia_curso_org_github_estado_valido"),
        ),
        sa.CheckConstraint(
            "permisos <@ ARRAY['tarea.administrar','correccion.asignar','nota.publicar','comunicacion.enviar','curso.administrar','equipo.administrar','mapeo.editar']::text[]",
            name=op.f("ck_membresia_curso_membresia_curso_permisos_catalogo_cerrado"),
        ),
        sa.CheckConstraint(
            "rol IN ('PROFESOR', 'AYUDANTE')", name=op.f("ck_membresia_curso_rol_valido")
        ),
        sa.CheckConstraint(
            "array_position(permisos, NULL) IS NULL",
            name=op.f("ck_membresia_curso_membresia_curso_permisos_sin_null"),
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_membresia_curso_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invitada_por"],
            ["usuario.id"],
            name=op.f("fk_membresia_curso_invitada_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["retirada_por"],
            ["usuario.id"],
            name=op.f("fk_membresia_curso_retirada_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_membresia_curso_usuario_id_usuario"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membresia_curso")),
    )
    op.create_index(
        "uq_membresia_curso_curso_id_usuario_id",
        "membresia_curso",
        ["curso_id", "usuario_id"],
        unique=True,
    )
    op.create_table(
        "salud_proveedor_curso",
        sa.Column("curso_id", sa.UUID(), nullable=True),
        sa.Column("proveedor", sa.Text(), nullable=False),
        sa.Column("detalle", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_salud_proveedor_curso_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_salud_proveedor_curso")),
    )
    op.create_table(
        "seccion",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("canvas_section_id", sa.BigInteger(), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("sis_section_id", sa.Text(), nullable=True),
        sa.Column("nonxlist_course_id", sa.BigInteger(), nullable=True),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("ciclos_ausente", sa.Integer(), nullable=False),
        sa.Column("sincronizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('ACTIVA', 'ELIMINADA')", name=op.f("ck_seccion_estado_valido")
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"], ["curso.id"], name=op.f("fk_seccion_curso_id_curso"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seccion")),
    )
    op.create_index(
        "uq_seccion_curso_id_canvas_section_id",
        "seccion",
        ["curso_id", "canvas_section_id"],
        unique=True,
    )
    op.create_table(
        "sincronizacion",
        sa.Column("curso_id", sa.UUID(), nullable=True),
        sa.Column("recurso", sa.Text(), nullable=False),
        sa.Column("resultado", sa.Text(), nullable=False),
        sa.Column("contadores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "resultado IN ('OK', 'PARCIAL', 'TRUNCADA', 'FALLIDA')",
            name=op.f("ck_sincronizacion_resultado_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_sincronizacion_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sincronizacion")),
    )
    op.create_table(
        "trabajo",
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("clave_idempotencia", sa.Text(), nullable=False),
        sa.Column("curso_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("intentos", sa.Integer(), nullable=False),
        sa.Column("max_intentos", sa.Integer(), nullable=False),
        sa.Column("proximo_intento_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tomado_por", sa.Text(), nullable=True),
        sa.Column("tomado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_error", sa.Text(), nullable=True),
        sa.Column("coste_api", sa.Integer(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terminado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_cancelacion", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('PENDIENTE', 'EN_CURSO', 'OK', 'REINTENTAR', 'BLOQUEADO', 'ESPERANDO_CREDENCIAL', 'ESPERANDO_LIMITE', 'REQUIERE_ATENCION', 'CANCELADO')",
            name=op.f("ck_trabajo_estado_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"], ["curso.id"], name=op.f("fk_trabajo_curso_id_curso"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trabajo")),
    )
    op.create_index(
        "ix_trabajo_estado_proximo_intento",
        "trabajo",
        ["estado", "proximo_intento_en"],
        unique=False,
    )
    op.create_index(
        "uq_trabajo_clave_idempotencia_no_terminal",
        "trabajo",
        ["clave_idempotencia"],
        unique=True,
        postgresql_where=sa.text("estado NOT IN ('OK', 'CANCELADO')"),
    )
    op.create_table(
        "trabajo_periodico",
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("curso_id", sa.UUID(), nullable=True),
        sa.Column("cadencia_segundos", sa.Integer(), nullable=False),
        sa.Column("proxima_ejecucion", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ultima_ejecucion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_trabajo_periodico_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trabajo_periodico")),
        sa.UniqueConstraint("tipo", "curso_id", name=op.f("uq_trabajo_periodico_tipo")),
    )
    op.create_table(
        "verificacion_canal",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("canal", sa.Text(), nullable=False),
        sa.Column("resultado", sa.Text(), nullable=True),
        sa.Column("evidencia", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verificado_por", sa.UUID(), nullable=True),
        sa.Column("verificado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_verificacion_canal_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["verificado_por"],
            ["usuario.id"],
            name=op.f("fk_verificacion_canal_verificado_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verificacion_canal")),
    )
    op.create_index(
        "uq_verificacion_canal_curso_id_canal",
        "verificacion_canal",
        ["curso_id", "canal"],
        unique=True,
    )
    op.create_table(
        "verificacion_vinculacion",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("ejecucion_id", sa.UUID(), nullable=False),
        sa.Column("item", sa.Text(), nullable=True),
        sa.Column("origen", sa.Text(), nullable=False),
        sa.Column("capacidad", sa.Text(), nullable=True),
        sa.Column("resultado", sa.Text(), nullable=False),
        sa.Column("detalle", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ejecutada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ejecutada_por", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(origen = 'CHECKLIST' AND item IS NOT NULL AND capacidad IS NULL) OR (origen = 'RUNTIME' AND capacidad IS NOT NULL AND item IS NULL)",
            name=op.f("ck_verificacion_vinculacion_origen_item_capacidad_coherentes"),
        ),
        sa.CheckConstraint(
            "origen IN ('CHECKLIST', 'RUNTIME')",
            name=op.f("ck_verificacion_vinculacion_origen_valido"),
        ),
        sa.CheckConstraint(
            "resultado IN ('CORRECTO', 'ADVERTENCIA', 'BLOQUEANTE', 'NO_VERIFICADO', 'VERIFICADO_A_MANO')",
            name=op.f("ck_verificacion_vinculacion_resultado_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_verificacion_vinculacion_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ejecutada_por"],
            ["usuario.id"],
            name=op.f("fk_verificacion_vinculacion_ejecutada_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verificacion_vinculacion")),
    )
    op.create_index(
        "ix_verificacion_vinculacion_curso_id_capacidad",
        "verificacion_vinculacion",
        ["curso_id", "capacidad"],
        unique=False,
    )
    op.create_index(
        "ix_verificacion_vinculacion_curso_id_ejecucion_id",
        "verificacion_vinculacion",
        ["curso_id", "ejecucion_id"],
        unique=False,
    )
    op.create_index(
        "ix_verificacion_vinculacion_curso_id_item",
        "verificacion_vinculacion",
        ["curso_id", "item"],
        unique=False,
    )
    op.create_table(
        "grupo",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("conjunto_grupos_id", sa.UUID(), nullable=False),
        sa.Column("canvas_group_id", sa.BigInteger(), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=True),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("lider_estudiante_id", sa.UUID(), nullable=True),
        sa.Column("is_full", sa.Boolean(), nullable=False),
        sa.Column("ciclos_ausente", sa.Integer(), nullable=False),
        sa.Column("sincronizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('ACTIVO', 'ELIMINADO')", name=op.f("ck_grupo_estado_valido")
        ),
        sa.ForeignKeyConstraint(
            ["conjunto_grupos_id"],
            ["conjunto_grupos.id"],
            name=op.f("fk_grupo_conjunto_grupos_id_conjunto_grupos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"], ["curso.id"], name=op.f("fk_grupo_curso_id_curso"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["lider_estudiante_id"],
            ["estudiante.id"],
            name=op.f("fk_grupo_lider_estudiante_id_estudiante"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grupo")),
    )
    op.create_index(
        "uq_grupo_curso_id_canvas_group_id", "grupo", ["curso_id", "canvas_group_id"], unique=True
    )
    op.create_table(
        "mapeo_github",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("estudiante_id", sa.UUID(), nullable=False),
        sa.Column("cuenta_github_id", sa.UUID(), nullable=True),
        sa.Column("origen", sa.Text(), nullable=True),
        sa.Column("confianza", sa.Text(), nullable=True),
        sa.Column("evidencia", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("motivo_invalidacion", sa.Text(), nullable=True),
        sa.Column("vigente_desde", sa.DateTime(timezone=True), nullable=True),
        sa.Column("vigente_hasta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creado_por", sa.UUID(), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revalidado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('SIN_DATO', 'RECIBIDO', 'NO_RESUELTO', 'NO_EXISTE', 'ES_ORGANIZACION', 'EN_CONFLICTO', 'VIGENTE', 'INVALIDADO', 'SUPERSEDIDO')",
            name=op.f("ck_mapeo_github_estado_valido"),
        ),
        sa.CheckConstraint(
            "motivo_invalidacion IS NULL OR motivo_invalidacion IN ('RENOMBRADO', 'CUENTA_ELIMINADA', 'LOGIN_REASIGNADO', 'ESTUDIANTE_RETIRADO', 'CUENTA_NO_ELEGIBLE')",
            name=op.f("ck_mapeo_github_motivo_invalidacion_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuario.id"],
            name=op.f("fk_mapeo_github_creado_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cuenta_github_id"],
            ["cuenta_github.id"],
            name=op.f("fk_mapeo_github_cuenta_github_id_cuenta_github"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_mapeo_github_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
            name=op.f("fk_mapeo_github_estudiante_id_estudiante"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mapeo_github")),
    )
    op.create_index(
        "uq_mapeo_github_curso_id_cuenta_github_id_vigente",
        "mapeo_github",
        ["curso_id", "cuenta_github_id"],
        unique=True,
        postgresql_where=sa.text("estado = 'VIGENTE'"),
    )
    op.create_index(
        "uq_mapeo_github_curso_id_estudiante_id_no_supersedido",
        "mapeo_github",
        ["curso_id", "estudiante_id"],
        unique=True,
        postgresql_where=sa.text("estado <> 'SUPERSEDIDO'"),
    )
    op.create_index(
        "uq_mapeo_github_curso_id_estudiante_id_vigente",
        "mapeo_github",
        ["curso_id", "estudiante_id"],
        unique=True,
        postgresql_where=sa.text("estado = 'VIGENTE'"),
    )
    op.create_table(
        "matricula",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("estudiante_id", sa.UUID(), nullable=False),
        sa.Column("seccion_id", sa.UUID(), nullable=False),
        sa.Column("canvas_enrollment_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=True),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("limitada_a_seccion", sa.Boolean(), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("sincronizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_matricula_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
            name=op.f("fk_matricula_estudiante_id_estudiante"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["seccion_id"],
            ["seccion.id"],
            name=op.f("fk_matricula_seccion_id_seccion"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matricula")),
    )
    op.create_index(
        "uq_matricula_curso_id_canvas_enrollment_id",
        "matricula",
        ["curso_id", "canvas_enrollment_id"],
        unique=True,
    )
    op.create_table(
        "sesion_membresia",
        sa.Column("sesion_id", sa.UUID(), nullable=False),
        sa.Column("membresia_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("refrescada_en", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["membresia_id"],
            ["membresia_curso.id"],
            name=op.f("fk_sesion_membresia_membresia_id_membresia_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sesion_id"],
            ["sesion.id"],
            name=op.f("fk_sesion_membresia_sesion_id_sesion"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("sesion_id", "membresia_id", name=op.f("pk_sesion_membresia")),
    )
    op.create_table(
        "pertenencia_grupo",
        sa.Column("grupo_id", sa.UUID(), nullable=False),
        sa.Column("estudiante_id", sa.UUID(), nullable=False),
        sa.Column("workflow_state", sa.Text(), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("activa_desde", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activa_hasta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ciclos_ausente", sa.Integer(), nullable=False),
        sa.Column("origen", sa.Text(), nullable=True),
        sa.Column("sincronizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "workflow_state IN ('accepted', 'invited', 'requested')",
            name=op.f("ck_pertenencia_grupo_workflow_state_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
            name=op.f("fk_pertenencia_grupo_estudiante_id_estudiante"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["grupo_id"],
            ["grupo.id"],
            name=op.f("fk_pertenencia_grupo_grupo_id_grupo"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pertenencia_grupo")),
    )
    op.create_index(
        "uq_pertenencia_grupo_grupo_id_estudiante_id",
        "pertenencia_grupo",
        ["grupo_id", "estudiante_id"],
        unique=True,
    )
    # --- Etapa P7: tarea individual, entrega unica y repositorio base ---
    op.create_table(
        "assignment_canvas",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("canvas_assignment_id", sa.BigInteger(), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("es_grupal", sa.Boolean(), nullable=False),
        sa.Column("group_category_id_canvas", sa.BigInteger(), nullable=True),
        sa.Column("only_visible_to_overrides", sa.Boolean(), nullable=False),
        sa.Column("publicada", sa.Boolean(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ciclos_ausente", sa.Integer(), nullable=False),
        sa.Column("ausente_en_canvas", sa.Boolean(), nullable=False),
        sa.Column("sincronizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_assignment_canvas_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignment_canvas")),
    )
    op.create_index(
        "uq_assignment_canvas_curso_id_canvas_assignment_id",
        "assignment_canvas",
        ["curso_id", "canvas_assignment_id"],
        unique=True,
    )
    op.create_table(
        "tarea",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("modalidad", sa.Text(), nullable=False),
        sa.Column("conjunto_grupos_id", sa.UUID(), nullable=True),
        sa.Column("repositorio_base_id", sa.UUID(), nullable=True),
        sa.Column("gitignore_template", sa.Text(), nullable=True),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("creada_por", sa.UUID(), nullable=True),
        sa.Column("activada_por", sa.UUID(), nullable=True),
        sa.Column("activada_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('BORRADOR', 'ACTIVA', 'INCONSISTENTE', 'CERRADA', 'ARCHIVADA')",
            name=op.f("ck_tarea_estado_valido"),
        ),
        sa.CheckConstraint(
            "modalidad IN ('INDIVIDUAL', 'GRUPAL')", name=op.f("ck_tarea_modalidad_valida")
        ),
        sa.CheckConstraint("length(slug) <= 24", name=op.f("ck_tarea_slug_longitud_maxima")),
        sa.ForeignKeyConstraint(
            ["activada_por"],
            ["usuario.id"],
            name=op.f("fk_tarea_activada_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["conjunto_grupos_id"],
            ["conjunto_grupos.id"],
            name=op.f("fk_tarea_conjunto_grupos_id_conjunto_grupos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["creada_por"],
            ["usuario.id"],
            name=op.f("fk_tarea_creada_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"], ["curso.id"], name=op.f("fk_tarea_curso_id_curso"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tarea")),
    )
    op.create_index("uq_tarea_curso_id_slug", "tarea", ["curso_id", "slug"], unique=True)
    op.create_table(
        "entrega",
        sa.Column("tarea_id", sa.UUID(), nullable=False),
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("canvas_assignment_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("puntos_posibles", sa.Float(), nullable=True),
        sa.Column("grading_type", sa.Text(), nullable=True),
        sa.Column("publicada", sa.Boolean(), nullable=False),
        sa.Column("moderated_grading", sa.Boolean(), nullable=False),
        sa.Column("anonymous_grading", sa.Boolean(), nullable=False),
        sa.Column("group_category_id_canvas", sa.BigInteger(), nullable=True),
        sa.Column("es_grupal_canvas", sa.Boolean(), nullable=False),
        sa.Column("only_visible_to_overrides", sa.Boolean(), nullable=False),
        sa.Column("due_at_base", sa.DateTime(timezone=True), nullable=True),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("huella_fechas", sa.LargeBinary(), nullable=True),
        sa.Column("canvas_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estado_validacion", sa.Text(), server_default="VIGENTE", nullable=False),
        sa.Column(
            "validaciones",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "advertencias",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("ciclos_ausente", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("detectada_ausente_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sincronizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "advertencias <@ ARRAY['LOCK_ANTES_DE_DUE','UNLOCK_DESPUES_DE_DUE',"
            "'FINAL_ANTES_QUE_PARCIAL','DOS_ENTREGAS_MISMA_FECHA']::text[]",
            name=op.f("ck_entrega_advertencias_catalogo_cerrado"),
        ),
        sa.CheckConstraint(
            "estado_validacion IN ('VIGENTE', 'VINCULADA_TRAS_EL_CIERRE', "
            "'ELIMINADA_EN_CANVAS', 'EXCLUIDA')",
            name=op.f("ck_entrega_estado_validacion_valido"),
        ),
        sa.CheckConstraint("tipo IN ('PARCIAL', 'FINAL')", name=op.f("ck_entrega_tipo_valido")),
        sa.CheckConstraint("orden >= 1", name=op.f("ck_entrega_orden_desde_uno")),
        sa.ForeignKeyConstraint(
            ["curso_id"], ["curso.id"], name=op.f("fk_entrega_curso_id_curso"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tarea_id"], ["tarea.id"], name=op.f("fk_entrega_tarea_id_tarea"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entrega")),
    )
    op.create_index(
        "uq_entrega_curso_id_canvas_assignment_id",
        "entrega",
        ["curso_id", "canvas_assignment_id"],
        unique=True,
    )
    op.create_index(
        "uq_entrega_tarea_id_final",
        "entrega",
        ["tarea_id"],
        unique=True,
        postgresql_where=sa.text("tipo = 'FINAL'"),
    )
    op.create_index("uq_entrega_tarea_id_orden", "entrega", ["tarea_id", "orden"], unique=True)
    op.create_index("uq_entrega_tarea_id_slug", "entrega", ["tarea_id", "slug"], unique=True)
    op.create_table(
        "repositorio_base",
        sa.Column("tarea_id", sa.UUID(), nullable=False),
        sa.Column("github_repo_id", sa.BigInteger(), nullable=True),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("url_html", sa.Text(), nullable=True),
        sa.Column("es_plantilla", sa.Boolean(), nullable=False),
        sa.Column("rama_por_defecto", sa.Text(), nullable=True),
        sa.Column("estado", sa.Text(), server_default="CREANDO", nullable=False),
        sa.Column("clase_error", sa.Text(), nullable=True),
        sa.Column("error_mensaje_literal", sa.Text(), nullable=True),
        sa.Column("inaccesible_desde", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creado_por", sa.UUID(), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('CREANDO', 'CREADO_VACIO', 'LISTO', 'ERROR', 'INACCESIBLE')",
            name=op.f("ck_repositorio_base_estado_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuario.id"],
            name=op.f("fk_repositorio_base_creado_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tarea_id"],
            ["tarea.id"],
            name=op.f("fk_repositorio_base_tarea_id_tarea"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositorio_base")),
    )
    op.create_index(
        "uq_repositorio_base_github_repo_id",
        "repositorio_base",
        ["github_repo_id"],
        unique=True,
        postgresql_where=sa.text("github_repo_id IS NOT NULL"),
    )
    op.create_index("uq_repositorio_base_tarea_id", "repositorio_base", ["tarea_id"], unique=True)
    # Ciclo tarea <-> repositorio_base (A-080): la FK de `tarea` se crea cuando
    # `repositorio_base` ya existe.
    op.create_foreign_key(
        "fk_tarea_repositorio_base_id_repositorio_base",
        "tarea",
        "repositorio_base",
        ["repositorio_base_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "archivo_repositorio_base",
        sa.Column("repositorio_base_id", sa.UUID(), nullable=False),
        sa.Column("ruta", sa.Text(), nullable=False),
        sa.Column("sha", sa.Text(), nullable=False),
        sa.Column("tamano_bytes", sa.Integer(), nullable=False),
        sa.Column("actualizado_por", sa.UUID(), nullable=True),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actualizado_por"],
            ["usuario.id"],
            name=op.f("fk_archivo_repositorio_base_actualizado_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["repositorio_base_id"],
            ["repositorio_base.id"],
            name=op.f("fk_archivo_repositorio_base_repositorio_base_id_repositorio_base"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_archivo_repositorio_base")),
    )
    op.create_index(
        "uq_archivo_repositorio_base_repositorio_base_id_ruta",
        "archivo_repositorio_base",
        ["repositorio_base_id", "ruta"],
        unique=True,
    )
    op.create_table(
        "visibilidad_entrega",
        sa.Column("entrega_id", sa.UUID(), nullable=False),
        sa.Column("estudiante_id", sa.UUID(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("origen", sa.Text(), nullable=False),
        sa.Column("sincronizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "origen IN ('TODOS', 'ASSIGNMENT_VISIBILITY', 'OVERRIDE', 'SUPUESTO')",
            name=op.f("ck_visibilidad_entrega_origen_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["entrega_id"],
            ["entrega.id"],
            name=op.f("fk_visibilidad_entrega_entrega_id_entrega"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
            name=op.f("fk_visibilidad_entrega_estudiante_id_estudiante"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("entrega_id", "estudiante_id", name=op.f("pk_visibilidad_entrega")),
    )
    # --- Etapa P8: aprovisionamiento, estado, aviso al estudiante y fechas ---
    op.create_table(
        "sujeto",
        sa.Column("tarea_id", sa.UUID(), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("estudiante_id", sa.UUID(), nullable=True),
        sa.Column("grupo_id", sa.UUID(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("desactivado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_desactivacion", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "motivo_desactivacion IS NULL OR motivo_desactivacion IN ('SIN_MATRICULA_ACTIVA', "
            "'SIN_VISIBILIDAD', 'GRUPO_DISUELTO', 'GRUPO_SIN_ACEPTADOS')",
            name=op.f("ck_sujeto_motivo_desactivacion_valido"),
        ),
        sa.CheckConstraint("tipo IN ('ESTUDIANTE', 'GRUPO')", name=op.f("ck_sujeto_tipo_valido")),
        sa.CheckConstraint(
            "(estudiante_id IS NULL) <> (grupo_id IS NULL)",
            name=op.f("ck_sujeto_exactamente_una_referencia"),
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
            name=op.f("fk_sujeto_estudiante_id_estudiante"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["grupo_id"], ["grupo.id"], name=op.f("fk_sujeto_grupo_id_grupo"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tarea_id"], ["tarea.id"], name=op.f("fk_sujeto_tarea_id_tarea"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sujeto")),
    )
    op.create_index(
        "uq_sujeto_tarea_id_tipo_referencia",
        "sujeto",
        ["tarea_id", "tipo", sa.text("coalesce(estudiante_id, grupo_id)")],
        unique=True,
    )
    op.create_table(
        "regla_fecha",
        sa.Column("entrega_id", sa.UUID(), nullable=False),
        sa.Column("alcance", sa.Text(), nullable=False),
        sa.Column("canvas_override_id", sa.BigInteger(), nullable=True),
        sa.Column("seccion_id", sa.UUID(), nullable=True),
        sa.Column("grupo_id", sa.UUID(), nullable=True),
        sa.Column("canvas_section_id", sa.BigInteger(), nullable=True),
        sa.Column("canvas_group_id", sa.BigInteger(), nullable=True),
        sa.Column("estudiante_ids", sa.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unlock_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lock_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("titulo", sa.Text(), nullable=True),
        sa.Column("sincronizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "alcance IN ('BASE', 'SECCION', 'GRUPO', 'ESTUDIANTES')",
            name=op.f("ck_regla_fecha_alcance_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["entrega_id"],
            ["entrega.id"],
            name=op.f("fk_regla_fecha_entrega_id_entrega"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["grupo_id"],
            ["grupo.id"],
            name=op.f("fk_regla_fecha_grupo_id_grupo"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["seccion_id"],
            ["seccion.id"],
            name=op.f("fk_regla_fecha_seccion_id_seccion"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regla_fecha")),
    )
    op.create_index(
        "uq_regla_fecha_entrega_id_base",
        "regla_fecha",
        ["entrega_id"],
        unique=True,
        postgresql_where=sa.text("alcance = 'BASE'"),
    )
    op.create_index(
        "uq_regla_fecha_entrega_id_canvas_override_id",
        "regla_fecha",
        ["entrega_id", "canvas_override_id"],
        unique=True,
        postgresql_where=sa.text("canvas_override_id IS NOT NULL"),
    )
    op.create_table(
        "repositorio",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("tarea_id", sa.UUID(), nullable=False),
        sa.Column("sujeto_id", sa.UUID(), nullable=False),
        sa.Column("github_repo_id", sa.BigInteger(), nullable=True),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("nombre_canonico", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("url_html", sa.Text(), nullable=True),
        sa.Column("rama_por_defecto", sa.Text(), nullable=True),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.Column("clase_error", sa.Text(), nullable=True),
        sa.Column("error_codigo", sa.Text(), nullable=True),
        sa.Column("error_mensaje_literal", sa.Text(), nullable=True),
        sa.Column("commit_inicial_sha", sa.Text(), nullable=True),
        sa.Column("intentos", sa.Integer(), nullable=False),
        sa.Column("sondeos_contenido", sa.SmallInteger(), nullable=False),
        sa.Column("proximo_intento_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reemplaza_a_id", sa.UUID(), nullable=True),
        sa.Column("recreado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("listo_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "error_codigo IS NULL OR error_codigo IN ('ORG_PROHIBE_CREAR_REPOS', 'ORG_EXIGE_2FA', "
            "'CUENTA_BLOQUEADA_POR_ORG', 'CUENTA_ELIMINADA', 'LOGIN_ES_ORGANIZACION', "
            "'NOMBRE_OCUPADO_POR_TERCERO', 'PERMISO_INSUFICIENTE')",
            name=op.f("ck_repositorio_error_codigo_valido"),
        ),
        sa.CheckConstraint(
            "estado IN ('ESPERANDO_INFORMACION', 'LISTO_PARA_CREAR', 'CREANDO', "
            "'CREADO_SIN_CONTENIDO', 'CONTENIDO_LISTO', 'CONFIGURANDO_ACCESOS', 'OPERATIVO', "
            "'DEGRADADO', 'BLOQUEADO', 'ESPERANDO_LIMITE', 'ERROR_TRANSITORIO', "
            "'ERROR_PERMANENTE', 'FUERA_DE_ALCANCE', 'INACCESIBLE', 'ARCHIVADO')",
            name=op.f("ck_repositorio_estado_valido"),
        ),
        sa.CheckConstraint(
            "motivo IS NULL OR motivo IN ('SIN_MAPEO_GITHUB', 'MAPEO_EN_CONFLICTO', "
            "'SIN_GRUPO_ASIGNADO', 'GRUPO_SIN_INTEGRANTES_ACEPTADOS', 'ESTUDIANTE_EN_DOS_GRUPOS', "
            "'TAREA_INCONSISTENTE', 'CURSO_EN_SOLO_LECTURA', 'FALTA_ACEPTAR_INVITACION_GITHUB', "
            "'INVITACION_EXPIRADA', 'INTEGRANTE_SIN_MAPEO', 'INTEGRANTE_PENDIENTE_EN_CANVAS', "
            "'SIN_ACCESO_DOCENTE', 'ERROR_AL_CONCEDER_ACCESO', 'BORRADO_EN_GITHUB', "
            "'TRANSFERIDO_FUERA_DE_LA_ORG', 'FUERA_DEL_ALCANCE_DE_LA_INSTALACION', "
            "'APP_SIN_ACCESO')",
            name=op.f("ck_repositorio_motivo_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_repositorio_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reemplaza_a_id"],
            ["repositorio.id"],
            name=op.f("fk_repositorio_reemplaza_a_id_repositorio"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sujeto_id"],
            ["sujeto.id"],
            name=op.f("fk_repositorio_sujeto_id_sujeto"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tarea_id"],
            ["tarea.id"],
            name=op.f("fk_repositorio_tarea_id_tarea"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositorio")),
    )
    op.create_index(
        "ix_repositorio_tarea_id_estado", "repositorio", ["tarea_id", "estado"], unique=False
    )
    op.create_index(
        "uq_repositorio_curso_id_nombre_no_inaccesible",
        "repositorio",
        ["curso_id", "nombre"],
        unique=True,
        postgresql_where=sa.text("estado <> 'INACCESIBLE'"),
    )
    op.create_index(
        "uq_repositorio_github_repo_id",
        "repositorio",
        ["github_repo_id"],
        unique=True,
        postgresql_where=sa.text("github_repo_id IS NOT NULL"),
    )
    op.create_index(
        "uq_repositorio_sujeto_id_no_inaccesible",
        "repositorio",
        ["sujeto_id"],
        unique=True,
        postgresql_where=sa.text("estado <> 'INACCESIBLE'"),
    )
    # A-163: nacio en P4 como esqueleto; aqui con su forma completa y su FK.
    op.create_table(
        "acceso_docente_repositorio",
        sa.Column("repositorio_id", sa.UUID(), nullable=False),
        sa.Column("membresia_id", sa.UUID(), nullable=True),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("via", sa.Text(), nullable=False),
        sa.Column("github_permission", sa.Text(), nullable=False),
        sa.Column("concedido_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('PENDIENTE', 'CONCEDIDO', 'REVOCADO', 'ERROR')",
            name=op.f("ck_acceso_docente_repositorio_estado_valido"),
        ),
        sa.CheckConstraint(
            "via IN ('TEAM', 'COLABORADOR')", name=op.f("ck_acceso_docente_repositorio_via_valida")
        ),
        sa.CheckConstraint(
            "github_permission = 'pull'", name=op.f("ck_acceso_docente_repositorio_solo_lectura")
        ),
        sa.CheckConstraint(
            "(via = 'TEAM') = (membresia_id IS NULL)",
            name=op.f("ck_acceso_docente_repositorio_membresia_segun_via"),
        ),
        sa.ForeignKeyConstraint(
            ["membresia_id"],
            ["membresia_curso.id"],
            name=op.f("fk_acceso_docente_repositorio_membresia_id_membresia_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["repositorio_id"],
            ["repositorio.id"],
            name=op.f("fk_acceso_docente_repositorio_repositorio_id_repositorio"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acceso_docente_repositorio")),
    )
    op.create_index(
        "uq_acceso_docente_repositorio_repositorio_membresia",
        "acceso_docente_repositorio",
        [
            "repositorio_id",
            sa.text("coalesce(membresia_id, '00000000-0000-0000-0000-000000000000'::uuid)"),
        ],
        unique=True,
    )
    op.create_table(
        "acceso_repositorio",
        sa.Column("repositorio_id", sa.UUID(), nullable=False),
        sa.Column("estudiante_id", sa.UUID(), nullable=False),
        sa.Column("cuenta_github_id", sa.UUID(), nullable=True),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("github_invitation_id", sa.BigInteger(), nullable=True),
        sa.Column("invitacion_html_url", sa.Text(), nullable=True),
        sa.Column("invitado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("aceptado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reenvios", sa.SmallInteger(), nullable=False),
        sa.Column("ultimo_reenvio_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_error", sa.Text(), nullable=True),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('SIN_MAPEO', 'POR_INVITAR', 'INVITADO', 'ACCESO_DIRECTO', 'ACEPTADO', "
            "'EXPIRADA', 'DESAPARECIDA', 'REVOCACION_PROPUESTA', 'REVOCACION_PROGRAMADA', "
            "'REVOCADO')",
            name=op.f("ck_acceso_repositorio_estado_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["cuenta_github_id"],
            ["cuenta_github.id"],
            name=op.f("fk_acceso_repositorio_cuenta_github_id_cuenta_github"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
            name=op.f("fk_acceso_repositorio_estudiante_id_estudiante"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["repositorio_id"],
            ["repositorio.id"],
            name=op.f("fk_acceso_repositorio_repositorio_id_repositorio"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acceso_repositorio")),
    )
    op.create_index(
        "uq_acceso_repositorio_repositorio_id_estudiante_id",
        "acceso_repositorio",
        ["repositorio_id", "estudiante_id"],
        unique=True,
    )
    op.create_table(
        "fecha_efectiva",
        sa.Column("entrega_id", sa.UUID(), nullable=False),
        sa.Column("sujeto_id", sa.UUID(), nullable=False),
        sa.Column("due_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("origen", sa.Text(), nullable=False),
        sa.Column("regla_fecha_id", sa.UUID(), nullable=True),
        sa.Column("ambigua", sa.Boolean(), nullable=False),
        sa.Column("calculada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("vigente_hasta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('VIGENTE', 'SUPERSEDIDA')", name=op.f("ck_fecha_efectiva_estado_valido")
        ),
        sa.CheckConstraint(
            "origen IN ('BASE', 'SECCION', 'GRUPO', 'ADHOC')",
            name=op.f("ck_fecha_efectiva_origen_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["entrega_id"],
            ["entrega.id"],
            name=op.f("fk_fecha_efectiva_entrega_id_entrega"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["regla_fecha_id"],
            ["regla_fecha.id"],
            name=op.f("fk_fecha_efectiva_regla_fecha_id_regla_fecha"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sujeto_id"],
            ["sujeto.id"],
            name=op.f("fk_fecha_efectiva_sujeto_id_sujeto"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fecha_efectiva")),
    )
    op.create_index(
        "ix_fecha_efectiva_estado_due_at_utc_vigente",
        "fecha_efectiva",
        ["estado", "due_at_utc"],
        unique=False,
        postgresql_where=sa.text("estado = 'VIGENTE'"),
    )
    op.create_index(
        "uq_fecha_efectiva_entrega_id_sujeto_id_vigente",
        "fecha_efectiva",
        ["entrega_id", "sujeto_id"],
        unique=True,
        postgresql_where=sa.text("estado = 'VIGENTE'"),
    )
    op.create_table(
        "mensaje_saliente",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("canal", sa.Text(), nullable=False),
        sa.Column("evento", sa.Text(), nullable=False),
        sa.Column("clave_idempotencia", sa.Text(), nullable=False),
        sa.Column("generacion", sa.SmallInteger(), nullable=False),
        sa.Column("reemplaza_a_id", sa.UUID(), nullable=True),
        sa.Column("tarea_id", sa.UUID(), nullable=True),
        sa.Column("sujeto_id", sa.UUID(), nullable=True),
        sa.Column("repositorio_id", sa.UUID(), nullable=True),
        sa.Column("estudiante_id", sa.UUID(), nullable=True),
        sa.Column("referencia", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("destinatario", sa.Text(), nullable=False),
        sa.Column("destinatario_canvas_user_id", sa.BigInteger(), nullable=True),
        sa.Column("plantilla", sa.Text(), nullable=False),
        sa.Column("plantilla_version", sa.SmallInteger(), nullable=False),
        sa.Column("asunto", sa.Text(), nullable=True),
        sa.Column("cuerpo_renderizado", sa.Text(), nullable=True),
        sa.Column("canal_efectivo", sa.Text(), nullable=True),
        sa.Column("origen", sa.Text(), nullable=False),
        sa.Column("disparado_por_trabajo_id", sa.UUID(), nullable=True),
        sa.Column("programado_para", sa.DateTime(timezone=True), nullable=True),
        sa.Column("caduca_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("motivo_estado", sa.Text(), nullable=True),
        sa.Column("intentos", sa.SmallInteger(), nullable=False),
        sa.Column("ultimo_codigo_http", sa.Integer(), nullable=True),
        sa.Column("ultimo_error_literal", sa.Text(), nullable=True),
        sa.Column("tomado_por", sa.Text(), nullable=True),
        sa.Column("tomado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canvas_id_resultante", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("enviado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "canal IN ('CANVAS_CONVERSACION', 'CANVAS_ANUNCIO', 'CANVAS_COMENTARIO', 'CORREO')",
            name=op.f("ck_mensaje_saliente_canal_valido"),
        ),
        sa.CheckConstraint(
            "estado IN ('PROGRAMADO', 'DIFERIDO', 'PENDIENTE', 'EN_CURSO', 'ENVIADO', "
            "'REINTENTAR', 'ESPERANDO_LIMITE', 'ESPERANDO_CREDENCIAL', 'BLOQUEADO', "
            "'REQUIERE_ATENCION', 'FALLIDO', 'CANCELADO', 'SUPRIMIDO', 'CADUCADO', 'RETRACTADO')",
            name=op.f("ck_mensaje_saliente_estado_valido"),
        ),
        sa.CheckConstraint(
            "origen IN ('AUTOMATICO', 'MANUAL', 'SISTEMA')",
            name=op.f("ck_mensaje_saliente_origen_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_mensaje_saliente_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
            name=op.f("fk_mensaje_saliente_estudiante_id_estudiante"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reemplaza_a_id"],
            ["mensaje_saliente.id"],
            name=op.f("fk_mensaje_saliente_reemplaza_a_id_mensaje_saliente"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["repositorio_id"],
            ["repositorio.id"],
            name=op.f("fk_mensaje_saliente_repositorio_id_repositorio"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sujeto_id"],
            ["sujeto.id"],
            name=op.f("fk_mensaje_saliente_sujeto_id_sujeto"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tarea_id"],
            ["tarea.id"],
            name=op.f("fk_mensaje_saliente_tarea_id_tarea"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mensaje_saliente")),
    )
    op.create_index(
        "ix_mensaje_saliente_estado_programado_para",
        "mensaje_saliente",
        ["estado", "programado_para"],
        unique=False,
    )
    op.create_index(
        "ix_mensaje_saliente_estudiante_id", "mensaje_saliente", ["estudiante_id"], unique=False
    )
    op.create_index(
        "ix_mensaje_saliente_repositorio_id", "mensaje_saliente", ["repositorio_id"], unique=False
    )
    op.create_index("ix_mensaje_saliente_tarea_id", "mensaje_saliente", ["tarea_id"], unique=False)
    op.create_index(
        "uq_mensaje_saliente_clave_idempotencia",
        "mensaje_saliente",
        ["clave_idempotencia"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # --- Etapa P8 ---
    op.drop_index("uq_mensaje_saliente_clave_idempotencia", table_name="mensaje_saliente")
    op.drop_index("ix_mensaje_saliente_tarea_id", table_name="mensaje_saliente")
    op.drop_index("ix_mensaje_saliente_repositorio_id", table_name="mensaje_saliente")
    op.drop_index("ix_mensaje_saliente_estudiante_id", table_name="mensaje_saliente")
    op.drop_index("ix_mensaje_saliente_estado_programado_para", table_name="mensaje_saliente")
    op.drop_table("mensaje_saliente")
    op.drop_index(
        "uq_fecha_efectiva_entrega_id_sujeto_id_vigente",
        table_name="fecha_efectiva",
        postgresql_where=sa.text("estado = 'VIGENTE'"),
    )
    op.drop_index(
        "ix_fecha_efectiva_estado_due_at_utc_vigente",
        table_name="fecha_efectiva",
        postgresql_where=sa.text("estado = 'VIGENTE'"),
    )
    op.drop_table("fecha_efectiva")
    op.drop_index(
        "uq_acceso_repositorio_repositorio_id_estudiante_id", table_name="acceso_repositorio"
    )
    op.drop_table("acceso_repositorio")
    op.drop_index(
        "uq_acceso_docente_repositorio_repositorio_membresia",
        table_name="acceso_docente_repositorio",
    )
    op.drop_table("acceso_docente_repositorio")
    op.drop_index(
        "uq_repositorio_sujeto_id_no_inaccesible",
        table_name="repositorio",
        postgresql_where=sa.text("estado <> 'INACCESIBLE'"),
    )
    op.drop_index(
        "uq_repositorio_github_repo_id",
        table_name="repositorio",
        postgresql_where=sa.text("github_repo_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_repositorio_curso_id_nombre_no_inaccesible",
        table_name="repositorio",
        postgresql_where=sa.text("estado <> 'INACCESIBLE'"),
    )
    op.drop_index("ix_repositorio_tarea_id_estado", table_name="repositorio")
    op.drop_table("repositorio")
    op.drop_index(
        "uq_regla_fecha_entrega_id_canvas_override_id",
        table_name="regla_fecha",
        postgresql_where=sa.text("canvas_override_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_regla_fecha_entrega_id_base",
        table_name="regla_fecha",
        postgresql_where=sa.text("alcance = 'BASE'"),
    )
    op.drop_table("regla_fecha")
    op.drop_index("uq_sujeto_tarea_id_tipo_referencia", table_name="sujeto")
    op.drop_table("sujeto")
    # --- Etapa P7 ---
    op.drop_table("visibilidad_entrega")
    op.drop_index(
        "uq_archivo_repositorio_base_repositorio_base_id_ruta",
        table_name="archivo_repositorio_base",
    )
    op.drop_table("archivo_repositorio_base")
    op.drop_constraint("fk_tarea_repositorio_base_id_repositorio_base", "tarea", type_="foreignkey")
    op.drop_index("uq_repositorio_base_tarea_id", table_name="repositorio_base")
    op.drop_index(
        "uq_repositorio_base_github_repo_id",
        table_name="repositorio_base",
        postgresql_where=sa.text("github_repo_id IS NOT NULL"),
    )
    op.drop_table("repositorio_base")
    op.drop_index("uq_entrega_tarea_id_slug", table_name="entrega")
    op.drop_index("uq_entrega_tarea_id_orden", table_name="entrega")
    op.drop_index(
        "uq_entrega_tarea_id_final",
        table_name="entrega",
        postgresql_where=sa.text("tipo = 'FINAL'"),
    )
    op.drop_index("uq_entrega_curso_id_canvas_assignment_id", table_name="entrega")
    op.drop_table("entrega")
    op.drop_index("uq_tarea_curso_id_slug", table_name="tarea")
    op.drop_table("tarea")
    op.drop_index(
        "uq_assignment_canvas_curso_id_canvas_assignment_id", table_name="assignment_canvas"
    )
    op.drop_table("assignment_canvas")
    # --- Etapas 0 a P6 ---
    op.drop_index("uq_pertenencia_grupo_grupo_id_estudiante_id", table_name="pertenencia_grupo")
    op.drop_table("pertenencia_grupo")
    op.drop_table("sesion_membresia")
    op.drop_index("uq_matricula_curso_id_canvas_enrollment_id", table_name="matricula")
    op.drop_table("matricula")
    op.drop_index(
        "uq_mapeo_github_curso_id_estudiante_id_vigente",
        table_name="mapeo_github",
        postgresql_where=sa.text("estado = 'VIGENTE'"),
    )
    op.drop_index(
        "uq_mapeo_github_curso_id_estudiante_id_no_supersedido",
        table_name="mapeo_github",
        postgresql_where=sa.text("estado <> 'SUPERSEDIDO'"),
    )
    op.drop_index(
        "uq_mapeo_github_curso_id_cuenta_github_id_vigente",
        table_name="mapeo_github",
        postgresql_where=sa.text("estado = 'VIGENTE'"),
    )
    op.drop_table("mapeo_github")
    op.drop_index("uq_grupo_curso_id_canvas_group_id", table_name="grupo")
    op.drop_table("grupo")
    op.drop_index(
        "ix_verificacion_vinculacion_curso_id_item", table_name="verificacion_vinculacion"
    )
    op.drop_index(
        "ix_verificacion_vinculacion_curso_id_ejecucion_id", table_name="verificacion_vinculacion"
    )
    op.drop_index(
        "ix_verificacion_vinculacion_curso_id_capacidad", table_name="verificacion_vinculacion"
    )
    op.drop_table("verificacion_vinculacion")
    op.drop_index("uq_verificacion_canal_curso_id_canal", table_name="verificacion_canal")
    op.drop_table("verificacion_canal")
    op.drop_table("trabajo_periodico")
    op.drop_index(
        "uq_trabajo_clave_idempotencia_no_terminal",
        table_name="trabajo",
        postgresql_where=sa.text("estado NOT IN ('OK', 'CANCELADO')"),
    )
    op.drop_index("ix_trabajo_estado_proximo_intento", table_name="trabajo")
    op.drop_table("trabajo")
    op.drop_table("sincronizacion")
    op.drop_index("uq_seccion_curso_id_canvas_section_id", table_name="seccion")
    op.drop_table("seccion")
    op.drop_table("salud_proveedor_curso")
    op.drop_index("uq_membresia_curso_curso_id_usuario_id", table_name="membresia_curso")
    op.drop_table("membresia_curso")
    op.drop_index(
        "uq_invitacion_equipo_curso_id_email_canonico_pendiente",
        table_name="invitacion_equipo",
        postgresql_where=sa.text("estado = 'PENDIENTE'"),
    )
    op.drop_table("invitacion_equipo")
    op.drop_table("intento_instalacion_github")
    op.drop_index("uq_instalacion_github_installation_id", table_name="instalacion_github")
    op.drop_index("uq_instalacion_github_curso_id", table_name="instalacion_github")
    op.drop_table("instalacion_github")
    op.drop_index("ix_incidencia_abierta", table_name="incidencia")
    op.drop_table("incidencia")
    op.drop_index("uq_estudiante_curso_id_canvas_user_id", table_name="estudiante")
    op.drop_table("estudiante")
    op.drop_index("uq_equipo_github_curso_curso_id", table_name="equipo_github_curso")
    op.drop_table("equipo_github_curso")
    op.drop_table("cursor_sincronizacion")
    op.drop_index(
        "uq_credencial_canvas_operativa_por_curso",
        table_name="credencial_canvas",
        postgresql_where=sa.text("orden_respaldo = 0"),
    )
    op.drop_index("uq_credencial_canvas_curso_id_usuario_id", table_name="credencial_canvas")
    op.drop_table("credencial_canvas")
    op.drop_index(
        "uq_conjunto_grupos_curso_id_canvas_group_category_id", table_name="conjunto_grupos"
    )
    op.drop_table("conjunto_grupos")
    op.drop_index("ix_bitacora_curso_id_creado_en", table_name="bitacora")
    op.drop_table("bitacora")
    op.drop_index("ix_sesion_usuario_id", table_name="sesion")
    op.drop_table("sesion")
    op.drop_index("uq_identidad_canvas_usuario_id_base_url", table_name="identidad_canvas_usuario")
    op.drop_index(
        "uq_identidad_canvas_base_url_canvas_user_id", table_name="identidad_canvas_usuario"
    )
    op.drop_table("identidad_canvas_usuario")
    op.drop_index("uq_curso_github_org_id", table_name="curso")
    op.drop_index("uq_curso_github_installation_id", table_name="curso")
    op.drop_table("curso")
    op.drop_index(
        "uq_usuario_cuenta_github_id",
        table_name="usuario",
        postgresql_where=sa.text("cuenta_github_id IS NOT NULL"),
    )
    op.drop_table("usuario")
    op.drop_table("resultado_invariante")
    op.drop_table("respaldo")
    op.drop_table("presupuesto_api")
    op.drop_table("estado_sistema")
    op.drop_index("uq_cuenta_github_github_user_id", table_name="cuenta_github")
    op.drop_table("cuenta_github")
    op.drop_table("cubo_tasa")
    # ### end Alembic commands ###
