"""Etapa F4: `version_entrega` y su inmutabilidad en la base.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25

Tabla nueva (cambio aditivo, S14.8.2) con las dos unicidades de A-084/A-204,
el indice GIN de `integrantes` y los CHECK de los catalogos cerrados y del
invariante estado -> etiqueta (RG-025).

El disparador `version_entrega_inmutable` es la garantia de CA-9.8-01 que no
depende de la aplicacion: rechaza todo `DELETE` y todo `UPDATE` que toque una
columna fuera de la lista cerrada de S9.8.1, que vuelva a poner `vigente` en
verdadero o que mueva `estado` fuera de sus dos transiciones (S9.6.3).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_FUNCION_INMUTABLE = """
CREATE OR REPLACE FUNCTION version_entrega_inmutable() RETURNS trigger AS $$
DECLARE
    antes jsonb;
    despues jsonb;
    mutables text[] := ARRAY[
        'vigente', 'motivo', 'tag_estado', 'tag_motivo', 'tag_error', 'tag_creado',
        'advertencias', 'estado'
    ];
    columna text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'version_entrega es evidencia: no se borra (A-030)';
    END IF;
    antes := to_jsonb(OLD);
    despues := to_jsonb(NEW);
    FOR columna IN SELECT jsonb_object_keys(despues) LOOP
        IF NOT (columna = ANY (mutables))
           AND (antes -> columna) IS DISTINCT FROM (despues -> columna) THEN
            RAISE EXCEPTION 'version_entrega.% es evidencia inmutable (S9.8.1)', columna;
        END IF;
    END LOOP;
    IF OLD.vigente = false AND NEW.vigente = true THEN
        RAISE EXCEPTION 'una version supersedida no vuelve a ser vigente';
    END IF;
    IF OLD.estado IS DISTINCT FROM NEW.estado AND NOT (
        (OLD.estado = 'CAPTURADA_SIN_TAG' AND NEW.estado = 'CAPTURADA')
        OR (OLD.estado = 'CAPTURADA' AND NEW.estado = 'CAPTURADA_SIN_TAG')
    ) THEN
        RAISE EXCEPTION 'transicion de estado no permitida: % -> %', OLD.estado, NEW.estado;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "version_entrega",
        sa.Column("entrega_id", sa.UUID(), nullable=False),
        sa.Column("sujeto_id", sa.UUID(), nullable=False),
        sa.Column("repositorio_id", sa.UUID(), nullable=True),
        sa.Column("intento", sa.Integer(), nullable=False),
        sa.Column("fecha_corte_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rama", sa.Text(), nullable=True),
        sa.Column("commit_sha", sa.Text(), nullable=True),
        sa.Column("commit_tree_sha", sa.Text(), nullable=True),
        sa.Column("commit_fecha_autor", sa.DateTime(timezone=True), nullable=True),
        sa.Column("commit_fecha_committer", sa.DateTime(timezone=True), nullable=True),
        sa.Column("commit_mensaje", sa.Text(), nullable=True),
        sa.Column("tag_nombre", sa.Text(), nullable=True),
        sa.Column("tag_estado", sa.Text(), nullable=False),
        sa.Column("tag_motivo", sa.Text(), nullable=True),
        sa.Column("tag_error", sa.Text(), nullable=True),
        sa.Column("tag_creado", sa.Boolean(), nullable=False),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.Column("motivo_repositorio", sa.Text(), nullable=True),
        sa.Column("vigente", sa.Boolean(), nullable=False),
        sa.Column("reemplaza_a_id", sa.UUID(), nullable=True),
        sa.Column("advertencias", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("verificacion", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("integrantes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("origen_captura", sa.Text(), nullable=False),
        sa.Column("creada_por_usuario_id", sa.UUID(), nullable=True),
        sa.Column("motivo_manual", sa.Text(), nullable=True),
        sa.Column("capturada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("github_repo_id", sa.BigInteger(), nullable=True),
        sa.Column("repositorio_full_name", sa.Text(), nullable=True),
        sa.Column("org_login", sa.Text(), nullable=True),
        sa.Column("installation_id", sa.BigInteger(), nullable=True),
        sa.Column("sujeto_tipo", sa.Text(), nullable=False),
        sa.Column("sujeto_etiqueta", sa.Text(), nullable=False),
        sa.Column("estado_sujeto_al_cierre", sa.Text(), nullable=True),
        sa.Column("seccion_nombre", sa.Text(), nullable=True),
        sa.Column("canvas_section_id", sa.BigInteger(), nullable=True),
        sa.Column("fecha_origen", sa.Text(), nullable=True),
        sa.Column("canvas_override_id", sa.BigInteger(), nullable=True),
        sa.Column("override_titulo", sa.Text(), nullable=True),
        sa.Column("fecha_ambigua", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(estado <> 'CAPTURADA' OR tag_estado = 'CREADO') AND (estado <> 'CAPTURADA_SIN_TAG' OR tag_estado IN ('PENDIENTE', 'CONFLICTO', 'FALLIDO')) AND (estado NOT IN ('SIN_COMMITS', 'SIN_REPOSITORIO', 'ERROR') OR tag_estado = 'NO_APLICA') AND (estado <> 'REVISAR' OR tag_estado IN ('CREADO', 'PENDIENTE', 'CONFLICTO', 'FALLIDO'))",
            name=op.f("ck_version_entrega_estado_implica_tag"),
        ),
        sa.CheckConstraint(
            "estado IN ('CAPTURADA', 'CAPTURADA_SIN_TAG', 'SIN_COMMITS', 'REVISAR', 'SIN_REPOSITORIO', 'ERROR')",
            name=op.f("ck_version_entrega_estado_valido"),
        ),
        sa.CheckConstraint(
            "estado IN ('SIN_COMMITS', 'SIN_REPOSITORIO', 'ERROR') OR commit_sha IS NOT NULL",
            name=op.f("ck_version_entrega_sha_si_hay_version"),
        ),
        sa.CheckConstraint(
            "motivo IS NULL OR motivo IN ('SIN_REPOSITORIO_AL_CIERRE', 'SUJETO_MATERIALIZADO_TRAS_EL_CIERRE', 'FECHA_ADELANTADA', 'FECHA_EXTENDIDA', 'CAPTURA_TARDIA_POR_ALCANCE')",
            name=op.f("ck_version_entrega_motivo_valido"),
        ),
        sa.CheckConstraint(
            "origen_captura = 'AUTOMATICA' OR (creada_por_usuario_id IS NOT NULL AND length(trim(motivo_manual)) >= 10)",
            name=op.f("ck_version_entrega_manual_con_actor_y_motivo"),
        ),
        sa.CheckConstraint(
            "origen_captura IN ('AUTOMATICA', 'MANUAL_AHORA', 'MANUAL_FECHA', 'MANUAL_SHA')",
            name=op.f("ck_version_entrega_origen_captura_valido"),
        ),
        sa.CheckConstraint(
            "tag_estado IN ('PENDIENTE', 'CREADO', 'CONFLICTO', 'FALLIDO', 'NO_APLICA')",
            name=op.f("ck_version_entrega_tag_estado_valido"),
        ),
        sa.CheckConstraint(
            "tag_motivo IS NULL OR tag_motivo IN ('REPOSITORIO_ARCHIVADO', 'LIMITE_API', 'SHA_DISTINTO', 'PERMISO_INSUFICIENTE', 'SIN_COMMITS', 'DESCONOCIDO', 'REPOSITORIO_INACCESIBLE')",
            name=op.f("ck_version_entrega_tag_motivo_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["creada_por_usuario_id"],
            ["usuario.id"],
            name=op.f("fk_version_entrega_creada_por_usuario_id_usuario"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["entrega_id"],
            ["entrega.id"],
            name=op.f("fk_version_entrega_entrega_id_entrega"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reemplaza_a_id"],
            ["version_entrega.id"],
            name=op.f("fk_version_entrega_reemplaza_a_id_version_entrega"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["repositorio_id"],
            ["repositorio.id"],
            name=op.f("fk_version_entrega_repositorio_id_repositorio"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sujeto_id"],
            ["sujeto.id"],
            name=op.f("fk_version_entrega_sujeto_id_sujeto"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_version_entrega")),
    )
    op.create_index(
        "ix_version_entrega_integrantes",
        "version_entrega",
        ["integrantes"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"integrantes": "jsonb_path_ops"},
    )
    op.create_index(
        "uq_version_entrega_entrega_id_sujeto_id_intento",
        "version_entrega",
        ["entrega_id", "sujeto_id", "intento"],
        unique=True,
    )
    op.create_index(
        "uq_version_entrega_entrega_id_sujeto_id_vigente",
        "version_entrega",
        ["entrega_id", "sujeto_id"],
        unique=True,
        postgresql_where=sa.text("vigente"),
    )
    # ### end Alembic commands ###
    op.execute(_FUNCION_INMUTABLE)
    op.execute(
        "CREATE TRIGGER version_entrega_inmutable BEFORE UPDATE OR DELETE ON version_entrega "
        "FOR EACH ROW EXECUTE FUNCTION version_entrega_inmutable()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS version_entrega_inmutable ON version_entrega")
    op.execute("DROP FUNCTION IF EXISTS version_entrega_inmutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_version_entrega_entrega_id_sujeto_id_vigente",
        table_name="version_entrega",
        postgresql_where=sa.text("vigente"),
    )
    op.drop_index("uq_version_entrega_entrega_id_sujeto_id_intento", table_name="version_entrega")
    op.drop_index(
        "ix_version_entrega_integrantes",
        table_name="version_entrega",
        postgresql_using="gin",
        postgresql_ops={"integrantes": "jsonb_path_ops"},
    )
    op.drop_table("version_entrega")
    # ### end Alembic commands ###
