"""Etapa F5: espejo de la actividad de GitHub.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-25

Tablas nuevas (cambio aditivo, S14.8.2): `evento_webhook`, `evento_push`,
`commit`, `autoria_commit` e `identidad_git` (SPEC 10 S10.2.10, S10.3.2,
S10.3.4), y `curso.ingesta_actividad_desde` (S10.2.6). La unicidad de
`autoria_commit` es sobre `(commit_id, coalesce(estudiante_id,
identidad_git_id))`, que es la clave primaria logica de S10.3.2.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evento_push",
        sa.Column("repositorio_id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.Text(), nullable=True),
        sa.Column("ref", sa.Text(), nullable=False),
        sa.Column("before_sha", sa.Text(), nullable=False),
        sa.Column("after_sha", sa.Text(), nullable=False),
        sa.Column("n_commits_payload", sa.Integer(), nullable=False),
        sa.Column("completado", sa.Boolean(), nullable=False),
        sa.Column("forzado", sa.Boolean(), nullable=False),
        sa.Column("divergido", sa.Boolean(), nullable=False),
        sa.Column("n_commits_huerfanos", sa.Integer(), nullable=False),
        sa.Column("recibido_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repositorio_id"],
            ["repositorio.id"],
            name=op.f("fk_evento_push_repositorio_id_repositorio"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evento_push")),
    )
    op.create_index(
        "ix_evento_push_repositorio_id_recibido_en",
        "evento_push",
        ["repositorio_id", "recibido_en"],
        unique=False,
    )
    op.create_table(
        "evento_webhook",
        sa.Column("delivery_id", sa.Text(), nullable=False),
        sa.Column("evento", sa.Text(), nullable=False),
        sa.Column("accion", sa.Text(), nullable=True),
        sa.Column("firma_valida", sa.Boolean(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("payload_bytes", sa.Integer(), nullable=False),
        sa.Column("payload_truncado", sa.Boolean(), nullable=False),
        sa.Column("repositorio_id", sa.UUID(), nullable=True),
        sa.Column("repositorio_base_id", sa.UUID(), nullable=True),
        sa.Column("motivo_no_resuelto", sa.Text(), nullable=True),
        sa.Column("recibido_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("procesado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('RECIBIDO', 'PENDIENTE_BLOQUE_2', 'PROCESADO', 'IGNORADO', 'SIN_DESTINO_PENDIENTE', 'DESCARTADO_ESPERADO', 'DESCARTADO_SIN_DESTINO', 'ERROR')",
            name=op.f("ck_evento_webhook_estado_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["repositorio_base_id"],
            ["repositorio_base.id"],
            name=op.f("fk_evento_webhook_repositorio_base_id_repositorio_base"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["repositorio_id"],
            ["repositorio.id"],
            name=op.f("fk_evento_webhook_repositorio_id_repositorio"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evento_webhook")),
    )
    op.create_index("uq_evento_webhook_delivery_id", "evento_webhook", ["delivery_id"], unique=True)
    op.create_table(
        "identidad_git",
        sa.Column("curso_id", sa.UUID(), nullable=False),
        sa.Column("repositorio_id", sa.UUID(), nullable=False),
        sa.Column("email_normalizado", sa.Text(), nullable=False),
        sa.Column("email_visto", sa.Text(), nullable=False),
        sa.Column("nombre_visto", sa.Text(), nullable=True),
        sa.Column("nombre_visto_ultimo", sa.Text(), nullable=True),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("estudiante_id", sa.UUID(), nullable=True),
        sa.Column("resuelta_por", sa.UUID(), nullable=True),
        sa.Column("resuelta_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("vigente_desde", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vigente_hasta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "estado IN ('SIN_RESOLVER', 'RESUELTA', 'NO_ES_ESTUDIANTE', 'SUPERSEDIDA')",
            name=op.f("ck_identidad_git_estado_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["curso_id"],
            ["curso.id"],
            name=op.f("fk_identidad_git_curso_id_curso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
            name=op.f("fk_identidad_git_estudiante_id_estudiante"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["repositorio_id"],
            ["repositorio.id"],
            name=op.f("fk_identidad_git_repositorio_id_repositorio"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resuelta_por"],
            ["usuario.id"],
            name=op.f("fk_identidad_git_resuelta_por_usuario"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identidad_git")),
    )
    op.create_index(
        "ix_identidad_git_curso_id_email_normalizado",
        "identidad_git",
        ["curso_id", "email_normalizado"],
        unique=False,
    )
    op.create_index(
        "uq_identidad_git_repositorio_id_email_vigente",
        "identidad_git",
        ["repositorio_id", "email_normalizado"],
        unique=True,
        postgresql_where=sa.text("estado <> 'SUPERSEDIDA'"),
    )
    op.create_table(
        "commit",
        sa.Column("repositorio_id", sa.UUID(), nullable=False),
        sa.Column("sha", sa.Text(), nullable=False),
        sa.Column("parent_shas", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("n_padres", sa.Integer(), nullable=True),
        sa.Column("es_merge", sa.Boolean(), nullable=False),
        sa.Column("rama_detectada", sa.Text(), nullable=True),
        sa.Column("en_rama_por_defecto", sa.Boolean(), nullable=False),
        sa.Column("mensaje_resumen", sa.Text(), nullable=True),
        sa.Column("autor_nombre", sa.Text(), nullable=True),
        sa.Column("autor_email", sa.Text(), nullable=True),
        sa.Column("autor_github_user_id", sa.BigInteger(), nullable=True),
        sa.Column("committer_github_user_id", sa.BigInteger(), nullable=True),
        sa.Column("fecha_autor", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fecha_committer", sa.DateTime(timezone=True), nullable=False),
        sa.Column("via_web", sa.Boolean(), nullable=True),
        sa.Column("adiciones", sa.Integer(), nullable=True),
        sa.Column("eliminaciones", sa.Integer(), nullable=True),
        sa.Column("archivos_tocados", sa.Integer(), nullable=True),
        sa.Column("sin_cambios", sa.Boolean(), nullable=True),
        sa.Column("identidad_git_id", sa.UUID(), nullable=True),
        sa.Column("estudiante_id", sa.UUID(), nullable=True),
        sa.Column("regla_atribucion", sa.Text(), nullable=False),
        sa.Column("motivo_exclusion", sa.Text(), nullable=False),
        sa.Column("autor_es_bot", sa.Boolean(), nullable=False),
        sa.Column("autor_es_docente", sa.Boolean(), nullable=False),
        sa.Column("huerfano", sa.Boolean(), nullable=False),
        sa.Column("huerfano_desde", sa.DateTime(timezone=True), nullable=True),
        sa.Column("historia_importada", sa.Boolean(), nullable=False),
        sa.Column("firma_estado", sa.Text(), nullable=False),
        sa.Column("firma_motivo", sa.Text(), nullable=True),
        sa.Column("origen_ingesta", sa.Text(), nullable=False),
        sa.Column("recibido_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingresado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enriquecido_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "firma_estado IN ('VERIFICADA', 'NO_VERIFICADA', 'DESCONOCIDA')",
            name=op.f("ck_commit_firma_estado_valido"),
        ),
        sa.CheckConstraint(
            "motivo_exclusion IN ('NINGUNO', 'MERGE', 'COMMIT_INICIAL', 'HUERFANO')",
            name=op.f("ck_commit_motivo_exclusion_valido"),
        ),
        sa.CheckConstraint(
            "origen_ingesta IN ('WEBHOOK', 'RELLENO_COMPARE', 'RECORRIDO', 'RECONCILIACION', 'BARRIDO', 'BACKFILL_INICIAL')",
            name=op.f("ck_commit_origen_ingesta_valido"),
        ),
        sa.CheckConstraint(
            "regla_atribucion IN ('AUTOR_GITHUB', 'EMAIL_NOREPLY', 'EMAIL_DIRECTO', 'IDENTIDAD_DOCENTE', 'SIN_ATRIBUIR')",
            name=op.f("ck_commit_regla_atribucion_valida"),
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
            name=op.f("fk_commit_estudiante_id_estudiante"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["identidad_git_id"],
            ["identidad_git.id"],
            name=op.f("fk_commit_identidad_git_id_identidad_git"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["repositorio_id"],
            ["repositorio.id"],
            name=op.f("fk_commit_repositorio_id_repositorio"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commit")),
    )
    op.create_index(
        "ix_commit_repositorio_id_estudiante_id_fecha",
        "commit",
        ["repositorio_id", "estudiante_id", "fecha_committer"],
        unique=False,
    )
    op.create_index(
        "ix_commit_repositorio_id_fecha_committer",
        "commit",
        ["repositorio_id", "fecha_committer"],
        unique=False,
    )
    op.create_index(
        "ix_commit_repositorio_id_rama_defecto_fecha",
        "commit",
        ["repositorio_id", "en_rama_por_defecto", "fecha_committer"],
        unique=False,
    )
    op.create_index(
        "uq_commit_repositorio_id_sha", "commit", ["repositorio_id", "sha"], unique=True
    )
    op.create_table(
        "autoria_commit",
        sa.Column("commit_id", sa.UUID(), nullable=False),
        sa.Column("estudiante_id", sa.UUID(), nullable=True),
        sa.Column("identidad_git_id", sa.UUID(), nullable=True),
        sa.Column("papel", sa.Text(), nullable=False),
        sa.Column("regla_atribucion", sa.Text(), nullable=False),
        sa.Column("confianza", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "confianza IS NULL OR confianza IN ('ALTA', 'MEDIA')",
            name=op.f("ck_autoria_commit_confianza_valida"),
        ),
        sa.CheckConstraint(
            "papel IN ('AUTOR', 'COAUTOR')", name=op.f("ck_autoria_commit_papel_valido")
        ),
        sa.CheckConstraint(
            "regla_atribucion IN ('AUTOR_GITHUB', 'EMAIL_NOREPLY', 'EMAIL_DIRECTO', 'IDENTIDAD_DOCENTE', 'SIN_ATRIBUIR')",
            name=op.f("ck_autoria_commit_regla_atribucion_valida"),
        ),
        sa.CheckConstraint(
            "estudiante_id IS NOT NULL OR identidad_git_id IS NOT NULL",
            name=op.f("ck_autoria_commit_acreditado_presente"),
        ),
        sa.ForeignKeyConstraint(
            ["commit_id"],
            ["commit.id"],
            name=op.f("fk_autoria_commit_commit_id_commit"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
            name=op.f("fk_autoria_commit_estudiante_id_estudiante"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["identidad_git_id"],
            ["identidad_git.id"],
            name=op.f("fk_autoria_commit_identidad_git_id_identidad_git"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_autoria_commit")),
    )
    op.create_index(
        "uq_autoria_commit_commit_id_acreditado",
        "autoria_commit",
        ["commit_id", sa.text("coalesce(estudiante_id, identidad_git_id)")],
        unique=True,
    )
    op.add_column(
        "curso", sa.Column("ingesta_actividad_desde", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("curso", "ingesta_actividad_desde")
    op.drop_index("uq_autoria_commit_commit_id_acreditado", table_name="autoria_commit")
    op.drop_table("autoria_commit")
    op.drop_index("uq_commit_repositorio_id_sha", table_name="commit")
    op.drop_index("ix_commit_repositorio_id_rama_defecto_fecha", table_name="commit")
    op.drop_index("ix_commit_repositorio_id_fecha_committer", table_name="commit")
    op.drop_index("ix_commit_repositorio_id_estudiante_id_fecha", table_name="commit")
    op.drop_table("commit")
    op.drop_index(
        "uq_identidad_git_repositorio_id_email_vigente",
        table_name="identidad_git",
        postgresql_where=sa.text("estado <> 'SUPERSEDIDA'"),
    )
    op.drop_index("ix_identidad_git_curso_id_email_normalizado", table_name="identidad_git")
    op.drop_table("identidad_git")
    op.drop_index("uq_evento_webhook_delivery_id", table_name="evento_webhook")
    op.drop_table("evento_webhook")
    op.drop_index("ix_evento_push_repositorio_id_recibido_en", table_name="evento_push")
    op.drop_table("evento_push")
    # ### end Alembic commands ###
