"""informe diario

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-26 00:45:26.466295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informe_diario',
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False, comment='Dia en la zona horaria del curso (curso.zona_horaria)'),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('ventana_desde_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ventana_hasta_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origen', sa.Text(), nullable=False),
    sa.Column('disparado_por_usuario_id', sa.UUID(), nullable=True),
    sa.Column('frescura', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contenido_html', sa.Text(), nullable=True),
    sa.Column('contenido_texto', sa.Text(), nullable=True),
    sa.Column('generado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("estado <> 'NO_GENERADO' OR motivo IS NOT NULL", name=op.f('ck_informe_diario_motivo_si_no_generado')),
    sa.CheckConstraint("estado IN ('GENERADO', 'SIN_TAREAS_ACTIVAS', 'NO_GENERADO')", name=op.f('ck_informe_diario_estado_valido')),
    sa.CheckConstraint("origen IN ('PROGRAMADO', 'MANUAL')", name=op.f('ck_informe_diario_origen_valido')),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], name=op.f('fk_informe_diario_curso_id_curso'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['disparado_por_usuario_id'], ['usuario.id'], name=op.f('fk_informe_diario_disparado_por_usuario_id_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_informe_diario'))
    )
    op.create_index('uq_informe_diario_curso_id_fecha', 'informe_diario', ['curso_id', 'fecha'], unique=True)
    op.create_table('suscripcion_informe',
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('origen_baja', sa.Text(), nullable=True),
    sa.Column('dada_de_baja_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("origen_baja IS NULL OR origen_baja IN ('USUARIO', 'TOPE_SUSCRIPTORES', 'RETIRO_MEMBRESIA', 'REBOTE')", name=op.f('ck_suscripcion_informe_origen_baja_valido')),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], name=op.f('fk_suscripcion_informe_curso_id_curso'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_suscripcion_informe_usuario_id_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('curso_id', 'usuario_id', name=op.f('pk_suscripcion_informe'))
    )
    op.add_column('mensaje_saliente', sa.Column('membresia_id', sa.UUID(), nullable=True))
    op.add_column('mensaje_saliente', sa.Column('disparado_por_usuario_id', sa.UUID(), nullable=True))
    op.add_column('mensaje_saliente', sa.Column('reserva', sa.Text(), nullable=True))
    op.add_column('mensaje_saliente', sa.Column('proveedor_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_mensaje_saliente_membresia_id'), 'mensaje_saliente', ['membresia_id'], unique=False)
    op.create_foreign_key(op.f('fk_mensaje_saliente_disparado_por_usuario_id_usuario'), 'mensaje_saliente', 'usuario', ['disparado_por_usuario_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_mensaje_saliente_membresia_id_membresia_curso'), 'mensaje_saliente', 'membresia_curso', ['membresia_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_mensaje_saliente_membresia_id_membresia_curso'), 'mensaje_saliente', type_='foreignkey')
    op.drop_constraint(op.f('fk_mensaje_saliente_disparado_por_usuario_id_usuario'), 'mensaje_saliente', type_='foreignkey')
    op.drop_index(op.f('ix_mensaje_saliente_membresia_id'), table_name='mensaje_saliente')
    op.drop_column('mensaje_saliente', 'proveedor_id')
    op.drop_column('mensaje_saliente', 'reserva')
    op.drop_column('mensaje_saliente', 'disparado_por_usuario_id')
    op.drop_column('mensaje_saliente', 'membresia_id')
    op.drop_table('suscripcion_informe')
    op.drop_index('uq_informe_diario_curso_id_fecha', table_name='informe_diario')
    op.drop_table('informe_diario')
    # ### end Alembic commands ###
