"""Etapa F6: agregados de seguimiento.

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-25

Tablas nuevas (cambio aditivo, S14.8.2): `metrica_repositorio_dia`,
`participacion_entrega` y `resumen_tarea` (SPEC 10 S10.4.2). Las escribe solo
`agregar_metricas`, recomputando y nunca incrementando.

`metrica_repositorio_dia.dia` es el dia del curso:
`(commit.fecha_committer AT TIME ZONE 'UTC' AT TIME ZONE curso.zona_horaria)::date`.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resumen_tarea",
        sa.Column("tarea_id", sa.UUID(), nullable=False),
        sa.Column("calculado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("contadores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tarea_id"],
            ["tarea.id"],
            name=op.f("fk_resumen_tarea_tarea_id_tarea"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumen_tarea")),
    )
    op.create_index("uq_resumen_tarea_tarea_id", "resumen_tarea", ["tarea_id"], unique=True)
    op.create_table(
        "metrica_repositorio_dia",
        sa.Column("repositorio_id", sa.UUID(), nullable=False),
        sa.Column("dia", sa.Date(), nullable=False),
        sa.Column("commits", sa.Integer(), nullable=False),
        sa.Column("commits_estudiantiles", sa.Integer(), nullable=False),
        sa.Column("commits_excluidos", sa.Integer(), nullable=False),
        sa.Column("commits_merge", sa.Integer(), nullable=False),
        sa.Column("commits_de_bot", sa.Integer(), nullable=False),
        sa.Column("commits_docentes", sa.Integer(), nullable=False),
        sa.Column("dias_activos_acumulados", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repositorio_id"],
            ["repositorio.id"],
            name=op.f("fk_metrica_repositorio_dia_repositorio_id_repositorio"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metrica_repositorio_dia")),
    )
    op.create_index(
        "uq_metrica_repositorio_dia_repositorio_id_dia",
        "metrica_repositorio_dia",
        ["repositorio_id", "dia"],
        unique=True,
    )
    op.create_table(
        "participacion_entrega",
        sa.Column("entrega_id", sa.UUID(), nullable=False),
        sa.Column("repositorio_id", sa.UUID(), nullable=False),
        sa.Column("estudiante_id", sa.UUID(), nullable=False),
        sa.Column("commits", sa.Integer(), nullable=False),
        sa.Column("adiciones", sa.Integer(), nullable=True),
        sa.Column("eliminaciones", sa.Integer(), nullable=True),
        sa.Column("dias_activos", sa.Integer(), nullable=False),
        sa.Column("primer_commit_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_commit_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("commits_coautorados", sa.Integer(), nullable=False),
        sa.Column("commits_sin_atribuir_repo", sa.Integer(), nullable=False),
        sa.Column("ventana_inicio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ventana_fin", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entrega_id"],
            ["entrega.id"],
            name=op.f("fk_participacion_entrega_entrega_id_entrega"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estudiante_id"],
            ["estudiante.id"],
            name=op.f("fk_participacion_entrega_estudiante_id_estudiante"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["repositorio_id"],
            ["repositorio.id"],
            name=op.f("fk_participacion_entrega_repositorio_id_repositorio"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participacion_entrega")),
    )
    op.create_index(
        "uq_participacion_entrega_entrega_repositorio_estudiante",
        "participacion_entrega",
        ["entrega_id", "repositorio_id", "estudiante_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_participacion_entrega_entrega_repositorio_estudiante",
        table_name="participacion_entrega",
    )
    op.drop_table("participacion_entrega")
    op.drop_index(
        "uq_metrica_repositorio_dia_repositorio_id_dia", table_name="metrica_repositorio_dia"
    )
    op.drop_table("metrica_repositorio_dia")
    op.drop_index("uq_resumen_tarea_tarea_id", table_name="resumen_tarea")
    op.drop_table("resumen_tarea")
    # ### end Alembic commands ###
