"""correccion

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-26 01:32:52.872125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignacion_correccion',
    sa.Column('entrega_id', sa.UUID(), nullable=False),
    sa.Column('sujeto_id', sa.UUID(), nullable=False),
    sa.Column('membresia_id', sa.UUID(), nullable=True),
    sa.Column('asignada_por', sa.UUID(), nullable=True),
    sa.Column('asignada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criterio', sa.Text(), nullable=False),
    sa.Column('criterio_seccion_id', sa.UUID(), nullable=True),
    sa.Column('desalineada_motivo', sa.Text(), nullable=True),
    sa.Column('desalineada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("criterio IN ('MANUAL', 'EQUITATIVO', 'SECCION', 'COPIA_ENTREGA_ANTERIOR')", name=op.f('ck_asignacion_correccion_criterio_valido')),
    sa.CheckConstraint("desalineada_motivo IS NULL OR desalineada_motivo IN ('CAMBIO_DE_SECCION', 'CAMBIO_DE_GRUPO')", name=op.f('ck_asignacion_correccion_desalineada_motivo_valido')),
    sa.ForeignKeyConstraint(['asignada_por'], ['membresia_curso.id'], name=op.f('fk_asignacion_correccion_asignada_por_membresia_curso'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['criterio_seccion_id'], ['seccion.id'], name=op.f('fk_asignacion_correccion_criterio_seccion_id_seccion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], name=op.f('fk_asignacion_correccion_entrega_id_entrega'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresia_curso.id'], name=op.f('fk_asignacion_correccion_membresia_id_membresia_curso'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sujeto_id'], ['sujeto.id'], name=op.f('fk_asignacion_correccion_sujeto_id_sujeto'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asignacion_correccion'))
    )
    op.create_index('ix_asignacion_correccion_membresia_id', 'asignacion_correccion', ['membresia_id'], unique=False)
    op.create_index('uq_asignacion_correccion_entrega_id_sujeto_id', 'asignacion_correccion', ['entrega_id', 'sujeto_id'], unique=True)
    op.create_table('estado_canvas_submission',
    sa.Column('entrega_id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('workflow_state', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('entered_score', sa.Numeric(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grader_id', sa.BigInteger(), nullable=True),
    sa.Column('excused', sa.Boolean(), nullable=True),
    sa.Column('late', sa.Boolean(), nullable=True),
    sa.Column('seconds_late', sa.Integer(), nullable=True),
    sa.Column('points_deducted', sa.Numeric(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gradeable', sa.Boolean(), nullable=True),
    sa.Column('origen', sa.Text(), server_default='CANVAS', nullable=False),
    sa.Column('sincronizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], name=op.f('fk_estado_canvas_submission_entrega_id_entrega'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], name=op.f('fk_estado_canvas_submission_estudiante_id_estudiante'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entrega_id', 'estudiante_id', name=op.f('pk_estado_canvas_submission'))
    )
    op.create_table('correccion',
    sa.Column('entrega_id', sa.UUID(), nullable=False),
    sa.Column('sujeto_id', sa.UUID(), nullable=False),
    sa.Column('version_entrega_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('trabajo_publicacion_id', sa.UUID(), nullable=True),
    sa.Column('nota_local', sa.Text(), nullable=True),
    sa.Column('rubrica_local', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('comentario_renderizado', sa.Text(), nullable=True),
    sa.Column('escalado_aplicado', sa.Boolean(), nullable=False),
    sa.Column('huella_rubrica', sa.LargeBinary(), nullable=True),
    sa.Column('rubrica_revisada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corrector_usuario_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lista_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publicable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('motivo_no_publicable', sa.Text(), nullable=True),
    sa.Column('version_desactualizada', sa.Boolean(), nullable=False),
    sa.Column('reclamo_abierto', sa.Boolean(), nullable=False),
    sa.Column('sin_commits', sa.Boolean(), nullable=False),
    sa.Column('reconocimiento_sin_codigo', sa.Boolean(), nullable=False),
    sa.Column('reconocimiento_sin_codigo_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipo_resultado', sa.Text(), nullable=False),
    sa.Column('publicada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('ultimo_error', sa.Text(), nullable=True),
    sa.Column('motivo_reapertura', sa.Text(), nullable=True),
    sa.Column('reabierta_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reabierta_por', sa.UUID(), nullable=True),
    sa.Column('banderas', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("estado IN ('SIN_CORRECTOR', 'ASIGNADA', 'EN_CURSO', 'LISTA_PARA_PUBLICAR', 'PUBLICANDO', 'PUBLICADA', 'PUBLICADA_CON_ADVERTENCIA', 'ERROR_PUBLICACION')", name=op.f('ck_correccion_estado_valido')),
    sa.CheckConstraint("motivo_no_publicable IS NULL OR motivo_no_publicable IN ('PERIODO_CERRADO', 'NO_GRADEABLE', 'NO_GRADED', 'GPA_SCALE', 'LETTER_GRADE_SIN_ESQUEMA', 'MODERADA_O_ANONIMA', 'ENTREGA_DESPUBLICADA', 'ENTREGA_ELIMINADA', 'SUJETO_EXCLUIDO', 'PUBLICACION_NO_AUTORIZADA')", name=op.f('ck_correccion_motivo_no_publicable_valido')),
    sa.CheckConstraint("tipo_resultado IN ('NOTA', 'EXCUSADA')", name=op.f('ck_correccion_tipo_resultado_valido')),
    sa.CheckConstraint('publicable OR motivo_no_publicable IS NOT NULL', name=op.f('ck_correccion_motivo_si_no_publicable')),
    sa.ForeignKeyConstraint(['corrector_usuario_id'], ['usuario.id'], name=op.f('fk_correccion_corrector_usuario_id_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], name=op.f('fk_correccion_entrega_id_entrega'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reabierta_por'], ['usuario.id'], name=op.f('fk_correccion_reabierta_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sujeto_id'], ['sujeto.id'], name=op.f('fk_correccion_sujeto_id_sujeto'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trabajo_publicacion_id'], ['trabajo.id'], name=op.f('fk_correccion_trabajo_publicacion_id_trabajo'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_entrega_id'], ['version_entrega.id'], name=op.f('fk_correccion_version_entrega_id_version_entrega'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correccion'))
    )
    op.create_index('uq_correccion_entrega_id_sujeto_id', 'correccion', ['entrega_id', 'sujeto_id'], unique=True)
    op.create_table('nota_interna_correccion',
    sa.Column('correccion_id', sa.UUID(), nullable=False),
    sa.Column('autor_membresia_id', sa.UUID(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('clase', sa.Text(), nullable=False),
    sa.Column('desenlace_reclamo', sa.Text(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(clase = 'RECLAMO_CERRADO') = (desenlace_reclamo IS NOT NULL)", name=op.f('ck_nota_interna_correccion_desenlace_solo_al_cerrar')),
    sa.CheckConstraint("clase IN ('NOTA', 'RECLAMO_ABIERTO', 'RECLAMO_CERRADO')", name=op.f('ck_nota_interna_correccion_clase_valida')),
    sa.CheckConstraint("desenlace_reclamo IS NULL OR desenlace_reclamo IN ('SIN_CAMBIO', 'NOTA_CORREGIDA', 'ERROR_DE_LA_APLICACION')", name=op.f('ck_nota_interna_correccion_desenlace_valido')),
    sa.ForeignKeyConstraint(['autor_membresia_id'], ['membresia_curso.id'], name=op.f('fk_nota_interna_correccion_autor_membresia_id_membresia_curso'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['correccion_id'], ['correccion.id'], name=op.f('fk_nota_interna_correccion_correccion_id_correccion'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nota_interna_correccion'))
    )
    op.create_index('ix_nota_interna_correccion_correccion_id', 'nota_interna_correccion', ['correccion_id'], unique=False)
    op.create_table('publicacion_nota',
    sa.Column('correccion_id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('intento', sa.SmallInteger(), nullable=False),
    sa.Column('payload_enviado', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('codigo_http', sa.Integer(), nullable=True),
    sa.Column('respuesta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_devuelto', sa.Numeric(), nullable=True),
    sa.Column('entered_score_devuelto', sa.Numeric(), nullable=True),
    sa.Column('grade_devuelto', sa.Text(), nullable=True),
    sa.Column('grader_id_reportado', sa.BigInteger(), nullable=True),
    sa.Column('late_policy_status_enviado', sa.Text(), nullable=False),
    sa.Column('publicado_por_usuario_id', sa.UUID(), nullable=False),
    sa.Column('credencial_canvas_id', sa.UUID(), nullable=True),
    sa.Column('intentada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['correccion_id'], ['correccion.id'], name=op.f('fk_publicacion_nota_correccion_id_correccion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['credencial_canvas_id'], ['credencial_canvas.id'], name=op.f('fk_publicacion_nota_credencial_canvas_id_credencial_canvas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], name=op.f('fk_publicacion_nota_estudiante_id_estudiante'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['publicado_por_usuario_id'], ['usuario.id'], name=op.f('fk_publicacion_nota_publicado_por_usuario_id_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publicacion_nota'))
    )
    op.create_index('uq_publicacion_nota_correccion_estudiante_intento', 'publicacion_nota', ['correccion_id', 'estudiante_id', 'intento'], unique=True)
    op.add_column('membresia_curso', sa.Column('peso_correccion', sa.SmallInteger(), nullable=True))
    op.add_column('membresia_curso', sa.Column('correccion_vista_en', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        op.f("ck_membresia_curso_peso_correccion_rango"),
        "membresia_curso",
        "peso_correccion IS NULL OR peso_correccion BETWEEN 0 AND 10",
    )
    # S12.2.4 y S12.2.6: la evidencia de publicacion y las notas internas son
    # append-only; un disparador rechaza cualquier UPDATE.
    for tabla in ("publicacion_nota", "nota_interna_correccion"):
        op.execute(
            f"""
CREATE OR REPLACE FUNCTION {tabla}_inmutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '{tabla} es append-only: no se modifica';
END;
$$ LANGUAGE plpgsql
"""
        )
        op.execute(
            f"CREATE TRIGGER {tabla}_inmutable BEFORE UPDATE ON {tabla} "
            f"FOR EACH ROW EXECUTE FUNCTION {tabla}_inmutable()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    for tabla in ("publicacion_nota", "nota_interna_correccion"):
        op.execute(f"DROP TRIGGER IF EXISTS {tabla}_inmutable ON {tabla}")
        op.execute(f"DROP FUNCTION IF EXISTS {tabla}_inmutable()")
    op.drop_constraint(
        op.f("ck_membresia_curso_peso_correccion_rango"), "membresia_curso", type_="check"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membresia_curso', 'correccion_vista_en')
    op.drop_column('membresia_curso', 'peso_correccion')
    op.drop_index('uq_publicacion_nota_correccion_estudiante_intento', table_name='publicacion_nota')
    op.drop_table('publicacion_nota')
    op.drop_index('ix_nota_interna_correccion_correccion_id', table_name='nota_interna_correccion')
    op.drop_table('nota_interna_correccion')
    op.drop_index('uq_correccion_entrega_id_sujeto_id', table_name='correccion')
    op.drop_table('correccion')
    op.drop_table('estado_canvas_submission')
    op.drop_index('uq_asignacion_correccion_entrega_id_sujeto_id', table_name='asignacion_correccion')
    op.drop_index('ix_asignacion_correccion_membresia_id', table_name='asignacion_correccion')
    op.drop_table('asignacion_correccion')
    # ### end Alembic commands ###
