"""comunicaciones

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-26 01:04:07.258663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantilla_mensaje',
    sa.Column('curso_id', sa.UUID(), nullable=True),
    sa.Column('clave', sa.Text(), nullable=False),
    sa.Column('canal', sa.Text(), nullable=False),
    sa.Column('asunto', sa.Text(), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creada_por', sa.UUID(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vigente_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("canal IN ('CANVAS_CONVERSACION', 'CANVAS_ANUNCIO', 'CANVAS_COMENTARIO', 'CORREO')", name=op.f('ck_plantilla_mensaje_canal_valido')),
    sa.CheckConstraint('char_length(asunto) <= 255', name=op.f('ck_plantilla_mensaje_asunto_corto')),
    sa.ForeignKeyConstraint(['creada_por'], ['usuario.id'], name=op.f('fk_plantilla_mensaje_creada_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], name=op.f('fk_plantilla_mensaje_curso_id_curso'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plantilla_mensaje'))
    )
    op.create_index('uq_plantilla_mensaje_vigente', 'plantilla_mensaje', [sa.text("coalesce(curso_id, '00000000-0000-0000-0000-000000000000'::uuid)"), 'clave', 'canal'], unique=True, postgresql_where=sa.text('vigente_hasta IS NULL'))
    op.create_table('ventana_supresion',
    sa.Column('curso_id', sa.UUID(), nullable=True),
    sa.Column('desde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hasta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('creada_por', sa.UUID(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['creada_por'], ['usuario.id'], name=op.f('fk_ventana_supresion_creada_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], name=op.f('fk_ventana_supresion_curso_id_curso'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ventana_supresion'))
    )
    op.create_table('supresion_comunicacion',
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('alcance', sa.Text(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('creada_por', sa.UUID(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vigente_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('levantada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('levantada_por', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("alcance IN ('TODAS_AUTOMATICAS', 'SOLO_RECORDATORIOS')", name=op.f('ck_supresion_comunicacion_alcance_valido')),
    sa.ForeignKeyConstraint(['creada_por'], ['usuario.id'], name=op.f('fk_supresion_comunicacion_creada_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], name=op.f('fk_supresion_comunicacion_curso_id_curso'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], name=op.f('fk_supresion_comunicacion_estudiante_id_estudiante'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['levantada_por'], ['usuario.id'], name=op.f('fk_supresion_comunicacion_levantada_por_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supresion_comunicacion'))
    )
    op.create_index('uq_supresion_comunicacion_vigente', 'supresion_comunicacion', ['curso_id', 'estudiante_id'], unique=True, postgresql_where=sa.text('levantada_en IS NULL'))
    op.create_table('regla_comunicacion',
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('tarea_id', sa.UUID(), nullable=True),
    sa.Column('alcance', sa.Text(), nullable=False),
    sa.Column('evento', sa.Text(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('actualizada_por', sa.UUID(), nullable=True),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(alcance = 'CURSO') = (evento = 'recordatorio_mapeo')", name=op.f('ck_regla_comunicacion_alcance_curso_mapeo')),
    sa.CheckConstraint("(alcance = 'CURSO') = (tarea_id IS NULL)", name=op.f('ck_regla_comunicacion_tarea_segun_alcance')),
    sa.CheckConstraint("alcance IN ('CURSO', 'TAREA')", name=op.f('ck_regla_comunicacion_alcance_valido')),
    sa.CheckConstraint("evento IN ('repositorio_disponible', 'invitacion_aceptada', 'recordatorio_mapeo', 'recordatorio_invitacion', 'proximidad_cierre', 'cambio_de_fecha', 'correccion_publicada')", name=op.f('ck_regla_comunicacion_evento_valido')),
    sa.ForeignKeyConstraint(['actualizada_por'], ['usuario.id'], name=op.f('fk_regla_comunicacion_actualizada_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], name=op.f('fk_regla_comunicacion_curso_id_curso'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tarea.id'], name=op.f('fk_regla_comunicacion_tarea_id_tarea'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regla_comunicacion'))
    )
    op.create_index('uq_regla_comunicacion_curso_tarea_evento', 'regla_comunicacion', ['curso_id', sa.text("coalesce(tarea_id, '00000000-0000-0000-0000-000000000000'::uuid)"), 'evento'], unique=True)
    op.create_table('cambio_fecha',
    sa.Column('entrega_id', sa.UUID(), nullable=False),
    sa.Column('huella_anterior', sa.Text(), nullable=False),
    sa.Column('huella_nueva', sa.Text(), nullable=False),
    sa.Column('ambito', sa.Text(), nullable=False),
    sa.Column('seccion_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('sujeto_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('detectado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ventana_cierra_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anunciado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mensaje_saliente_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("ambito IN ('CURSO', 'SECCION', 'GRUPO', 'ADHOC')", name=op.f('ck_cambio_fecha_ambito_valido')),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], name=op.f('fk_cambio_fecha_entrega_id_entrega'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mensaje_saliente_id'], ['mensaje_saliente.id'], name=op.f('fk_cambio_fecha_mensaje_saliente_id_mensaje_saliente'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cambio_fecha'))
    )
    op.create_index('ix_cambio_fecha_entrega_id', 'cambio_fecha', ['entrega_id'], unique=False)
    op.add_column('curso', sa.Column('comunicaciones_salientes', sa.Text(), server_default='ACTIVAS', nullable=False))
    op.add_column('curso', sa.Column('suspension_motivo', sa.Text(), nullable=True))
    op.add_column('curso', sa.Column('suspension_desde', sa.DateTime(timezone=True), nullable=True))
    op.add_column('curso', sa.Column('suspension_por', sa.UUID(), nullable=True))
    op.add_column('curso', sa.Column('modo_escritura', sa.Text(), server_default='COMPLETO', nullable=False))
    op.create_foreign_key(op.f('fk_curso_suspension_por_usuario'), 'curso', 'usuario', ['suspension_por'], ['id'], ondelete='RESTRICT')
    op.add_column('mensaje_saliente', sa.Column('entrega_id', sa.UUID(), nullable=True))
    op.add_column('mensaje_saliente', sa.Column('es_prueba', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mensaje_saliente', sa.Column('cuerpo_truncado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mensaje_saliente', sa.Column('canvas_html_url', sa.Text(), nullable=True))
    op.add_column('mensaje_saliente', sa.Column('retraccion_solicitada', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mensaje_saliente', sa.Column('retractado_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mensaje_saliente', sa.Column('retractado_por', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_mensaje_saliente_entrega_id'), 'mensaje_saliente', ['entrega_id'], unique=False)
    # Los CHECK sobre tablas existentes no los detecta la autogeneracion.
    op.create_check_constraint(
        op.f("ck_curso_comunicaciones_salientes_valida"),
        "curso",
        "comunicaciones_salientes IN ('ACTIVAS', 'SUSPENDIDAS')",
    )
    op.create_check_constraint(
        op.f("ck_curso_modo_escritura_valido"),
        "curso",
        "modo_escritura IN ('COMPLETO', 'SOLO_LECTURA')",
    )
    op.create_check_constraint(
        op.f("ck_curso_solo_lectura_suspende"),
        "curso",
        "NOT (modo_escritura = 'SOLO_LECTURA' AND comunicaciones_salientes = 'ACTIVAS')",
    )
    op.create_check_constraint(
        op.f("ck_mensaje_saliente_reserva_valida"),
        "mensaje_saliente",
        "reserva IS NULL OR reserva IN ('INFORME', 'OPERATIVO', 'MARGEN')",
    )
    op.create_foreign_key(op.f('fk_mensaje_saliente_entrega_id_entrega'), 'mensaje_saliente', 'entrega', ['entrega_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_mensaje_saliente_retractado_por_usuario'), 'mensaje_saliente', 'usuario', ['retractado_por'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    for nombre, tabla in (
        ("ck_mensaje_saliente_reserva_valida", "mensaje_saliente"),
        ("ck_curso_solo_lectura_suspende", "curso"),
        ("ck_curso_modo_escritura_valido", "curso"),
        ("ck_curso_comunicaciones_salientes_valida", "curso"),
    ):
        op.drop_constraint(op.f(nombre), tabla, type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_mensaje_saliente_retractado_por_usuario'), 'mensaje_saliente', type_='foreignkey')
    op.drop_constraint(op.f('fk_mensaje_saliente_entrega_id_entrega'), 'mensaje_saliente', type_='foreignkey')
    op.drop_index(op.f('ix_mensaje_saliente_entrega_id'), table_name='mensaje_saliente')
    op.drop_column('mensaje_saliente', 'retractado_por')
    op.drop_column('mensaje_saliente', 'retractado_en')
    op.drop_column('mensaje_saliente', 'retraccion_solicitada')
    op.drop_column('mensaje_saliente', 'canvas_html_url')
    op.drop_column('mensaje_saliente', 'cuerpo_truncado')
    op.drop_column('mensaje_saliente', 'es_prueba')
    op.drop_column('mensaje_saliente', 'entrega_id')
    op.drop_constraint(op.f('fk_curso_suspension_por_usuario'), 'curso', type_='foreignkey')
    op.drop_column('curso', 'modo_escritura')
    op.drop_column('curso', 'suspension_por')
    op.drop_column('curso', 'suspension_desde')
    op.drop_column('curso', 'suspension_motivo')
    op.drop_column('curso', 'comunicaciones_salientes')
    op.drop_index('ix_cambio_fecha_entrega_id', table_name='cambio_fecha')
    op.drop_table('cambio_fecha')
    op.drop_index('uq_regla_comunicacion_curso_tarea_evento', table_name='regla_comunicacion')
    op.drop_table('regla_comunicacion')
    op.drop_index('uq_supresion_comunicacion_vigente', table_name='supresion_comunicacion', postgresql_where=sa.text('levantada_en IS NULL'))
    op.drop_table('supresion_comunicacion')
    op.drop_table('ventana_supresion')
    op.drop_index('uq_plantilla_mensaje_vigente', table_name='plantilla_mensaje', postgresql_where=sa.text('vigente_hasta IS NULL'))
    op.drop_table('plantilla_mensaje')
    # ### end Alembic commands ###
